import numpy as np
import logging

from funcs import check_position
from path import Path
import matplotlib.pyplot as plt

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

def shooting_move(ens, level=0):
    """ Performs a shooting move in the ensemble.

    A random phasepoint of the last_accepted path in the ensemble is chosen,
    excluding the first and last phasepoints. This new phasepoint, called the
    shootpoint, is given new velocities drawn from the Maxwell-Boltzmann
    distribution. A new path is generated by propagating the shootpoint
    backwards and forwards in time. Note that backwards propagation is done
    by reversing the velocities of the shootpoint.

    To obey detailed balance, the new path is accepted with probability
    min(1, len(old_path)/len(new_path)). For efficiency sake, we draw a random
    number between 0 and 1 and propagate the new_path until len(old_path)/Q.

    The new_path is checked whether it is an acceptable path for the ensemble.

    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble in which the shooting move is performed
    level : int
        The level of the path to shoot from in ensemble ens. Default is 0.

    Returns
    -------
    success : string
        String indicating whether the shooting move was successful:
        - "ACC": Accepted
        - "NCR": Not crossing (path doesn't satisfy ensemble crossing conditions)
        - "FWI"/"BWI": Forward/Backward wrong interface
        - "FTL"/"BTL": Forward/Backward too long
        - "ILL": Illegal pathtype for primed ensemble
    new_path : :py:class:`Path` object
        New path generated by the shooting move

    """
    path = ens.paths[level]  # last accepted path
    pathlen = len(path.phasepoints)
    
    # Calculate maximum path length based on acceptance probability
    # Ensures detailed balance by limiting path length proportionally to old path
    shoot_maxlen = min(int((pathlen-2)/np.random.rand()) + 2, ens.max_len)
    
    # Choose random shooting point, excluding endpoints
    sh_id = np.random.randint(1, pathlen-1)
    
    # Create shooting point with new velocities but original position
    shootpoint = (path.phasepoints[sh_id][0],
                  ens.engine.draw_velocities())
    # We will not recalculate the orderparameter for this phasepoint, as 
    # external engines may save phasepoints at a lower precision. This can 
    # lead to the recalculated phasepoint shifting position w.r.t. an interface,
    # resulting in all sorts of nasty problems.
    # shootpoint_op = ens.orderparameter.calculate(shootpoint)
    shootpoint_op = path.orders[sh_id]
    
    logger.debug("Shooting from ph {} (idx: {}) with op {}".format(
        shootpoint, sh_id, shootpoint_op))
    
    # We propagate backwards first since the backward constraints (starting conditions)
    # are often more restrictive than the ending conditions
    # maxlen = shoot_maxlen-2 because shootpoint is not included in list
    bw_status, bw_tuple = propagate(ens, shootpoint, -1., shoot_maxlen-2)
    
    # If backward propagation fails, return the status and partial path
    if bw_status != "ACC": 
        logger.debug("Backwards propagation not successful: {}".format(
            bw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0]+[shootpoint], 
                                   bw_tuple[1]+[shootpoint_op], 
                                   ens.id))
        return bw_status, Path(bw_tuple[0]+[shootpoint],
                               bw_tuple[1]+[shootpoint_op],
                               ens.id)
    
    # If backward propagation is successful, continue with forward propagation
    # Adjust remaining max length based on backward path length
    fw_status, fw_tuple = propagate(ens, shootpoint, 1.,
                                    shoot_maxlen-len(bw_tuple[0])-1)
    
    # If forward propagation fails, return with partial path
    if fw_status != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(
            fw_status))
        return fw_status, Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id)
    
    # Both propagations successful, construct the complete path
    new_path = Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id)
    
    # For primed PPTIS ensembles, check for illegal path types
    if ens.ens_type in ['PPTIS_0plusmin_primed', 'PPTIS_Nplusmin_primed']:
        ptype = ens.get_ptype(new_path)
        if ptype in ens.illegal_pathtypes:
            logger.info("Illegal pathtype {} for primed ensemble".format(ptype))
            new_path.meta = [ptype, 0, "ILL", shootpoint_op]
            return "ILL", new_path
    
    # Final check: verify the path meets the crossing conditions
    if not ens.check_cross(new_path):
        logger.debug("New path does not satisfy ensemble crossing conditions")
        return "NCR", new_path
    else:
        logger.debug("New path satisfies ensemble crossing conditions.")
        return "ACC", new_path

def swap(ensembles, idx):
    """ Performs a swap move between the last paths of two ensembles.
    
    For (RE)TIS simulations, this function attempts to swap paths between
    adjacent ensembles. It checks whether the path of ensembles[idx] satisfies 
    the crossing conditions of ensembles[idx+1].

    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of ensembles present in the simulation
    idx: int
        Index of the ensemble to swap with the next ensemble in the list

    Returns
    -------
    success : string
        String indicating whether the swap move was successful ("ACC" or "NCR")
    path1 : :py:class:`Path` object
        Path from the second ensemble (ensembles[idx+1])
    path2 : :py:class:`Path` object
        Path from the first ensemble (ensembles[idx])

    """
    # Check if the path from idx ensemble can be moved to idx+1 ensemble
    if ensembles[idx+1].check_path(ensembles[idx].paths[0]):
        return "ACC", ensembles[idx+1].paths[0], ensembles[idx].paths[0]
    else:
        return "NCR", ensembles[idx+1].paths[0], ensembles[idx].paths[0]

def swap_zero(ensembles):
    """ Performs a swap move between the [0^-] (or [0^-']) and [0^+] (or [0^+'])
    ensembles.
    
    This specialized swap requires integration since the ensembles represent
    different regions of phase space. The function:
    
    1. Extends the [0^-] path into the [0^+] region by propagating forward
    2. Extends the [0^+] path into the [0^-] region by propagating backward
    3. Checks if both new paths satisfy their respective ensemble conditions

    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of ensembles present in the simulation, where ensembles[0] is 
        the [0^-] ensemble and ensembles[1] is the [0^+] ensemble

    Returns
    -------
    success : string
        String indicating whether the swap move was successful:
        - "ACC": Accepted
        - "NCR": Not crossing (path doesn't satisfy ensemble crossing conditions)
        - "SWD": Swap wrong direction
        - "ILL": Illegal pathtype for primed ensemble
        - Or propagation error code
    new_path_0m : :py:class:`Path` object
        New path for the [0^-] ensemble
    new_path_0p : :py:class:`Path` object
        New path for the [0^+] ensemble

    """
    ens0, ens1 = ensembles[0], ensembles[1]    
    # 1. create the new path for the [0^+] ensemble.
    # Cut the last two phasepoints of the [0^-] path, and propagate the last
    # phasepoint forwards in time. Remember, the shoot phasepoint is already
    # present in ph1 and op1 via cut_extremal_phasepoints.
    ph1, op1, sh1 = cut_extremal_phasepoints(ens0, 1.)
    
    # Check if the last point is beyond the left interface (required for swap)
    if op1[-1][0] <= ens0.intfs["L"]:
        logger.debug("Swap not allowed - last point not beyond left interface")
        return "SWD", ens0.paths[0], ens1.paths[0]
    
    # Propagate forward to create new [0^+] path
    status1, tuple1 = propagate(ens1, sh1, 1., ens1.max_len - 2)
    
    # If forward propagation fails, return with partial path
    if status1 != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(status1))
        return status1, ens1.paths[0], Path(ph1 + tuple1[0],
                                          op1 + tuple1[1],
                                          ens1.id)
    
    # Create complete new [0^+] path
    new_path1 = Path(ph1 + tuple1[0], op1 + tuple1[1], ens1.id)
    
    # Check if path is valid for the [0^+] ensemble
    ptype1 = ens1.get_ptype(new_path1)
    if not ens1.check_cross(new_path1):
        logger.warning("New path [0^+] doesn't satisfy ens cross conditions")
        return "NCR", ens1.paths[0], new_path1
    
    # For primed ensembles, check for illegal path types
    if ptype1 in ens1.illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype1))
        new_path1.meta = [ptype1, 0, "ILL", op1]
        return "ILL", ens0.paths[0], (new_path1, ptype1)
        # 2. create the new path for the [0^-] ensemble.
    # Cut the first two phasepoints of the [0^+] path, and propagate the first
    # phasepoint backwards in time. Remember, the shoot phasepoint is already
    # present in ph0 and op0 via cut_extremal_phasepoints.
    ph0, op0, sh0 = cut_extremal_phasepoints(ens1, -1.)
    
    # Check if the first two points are not beyond the right interface
    if op0[0][0] >= ens1.intfs["R"] or op0[1][0] >= ens1.intfs["R"]:
        logger.debug("Swap not allowed - points beyond right interface")
        return "SWD", ens0.paths[0], new_path1
    
    # Propagate backward to create new [0^-] path
    status0, tuple0 = propagate(ens0, sh0, -1., ens0.max_len - 2)
    
    # If backward propagation fails, return with partial paths
    if status0 != "ACC":
        logger.debug("Backwards propagation not successful: {}".format(status0))
        return status0, Path(tuple0[0] + ph0, tuple0[1] + op0, ens0.id),\
            new_path1
    
    # Create complete new [0^-] path
    new_path0 = Path(tuple0[0] + ph0, tuple0[1] + op0, ens0.id)
    
    # Check if path is valid for the [0^-] ensemble
    if not ens0.check_cross(new_path0):
        logger.warning("New path [0^-] doesn't satisfy ens cross conditions")
        return "NCR", new_path0, new_path1
    
    # Both paths are valid, swap successful
    return "ACC", new_path0, new_path1

def repptis_swap(ensembles, idx):
    """ Performs a swapping move in REPPTIS simulations between adjacent
    PPTIS ensembles.
    
    The function follows these steps:
    1. Determine propagation directions for both paths and check compatibility
    2. For compatible directions, create path segments in the overlapping region
    3. Propagate these segments to create complete paths for both ensembles
    4. Verify the new paths meet their respective ensemble conditions
    
    For each path creation:
    - The [i^+-] path gets the LM region from the [(i+1)^+-] path
    - The [(i+1)^+-] path gets the MR region from the [i^+-] path
    
    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of ensembles present in the simulation
    idx: int
        Index of the ensemble whose path is swapped with the next ensemble

    Returns
    -------
    success : string
        String indicating whether the swap move was successful:
        - "ACC": Accepted
        - "NCR": Not crossing (path doesn't satisfy crossing conditions)
        - "SWD": Swap wrong direction (incompatible path types)
        - Or propagation error code
    new_path_i : :py:class:`Path` object
        New path for the i-th ensemble
    new_path_i1 : :py:class:`Path` object
        New path for the (i+1)-th ensemble

    """
    logger.info("Swapping: {} <-> {}".format(idx, idx+1))
    
    # For idx=0, perform the specialized swap_zero move
    if idx == 0:
        return swap_zero(ensembles)
    
    # Get the two ensembles to swap
    ens0, ens1 = ensembles[idx], ensembles[idx+1]
    
    # Choose propagation directions and check compatibility
    allowed, propdir0, propdir1, path0_type, path1_type = \
        check_propagation_directions(ens0, ens1)
    
    # If directions are incompatible, reject the move
    if not allowed:
        msg = "Proposed move is not allowed. Incompatible path types and "
        msg += "propagation directions."
        logger.debug(msg)
        return 'SWD', ens0.paths[0], ens1.paths[0]  # Swap Wrong Direction
    
    # Log the attempted swap
    msg = "Attempting swap of {} and {} paths with propdirs {} and {}."
    logger.debug(msg.format(path0_type, path1_type, propdir0, propdir1))
    
    # Convert propagation direction to numerical value (1 for forward, -1 for backward)
    reverse0 = 1. if propdir0 == 'forwards' else -1.
    reverse1 = 1. if propdir1 == 'forwards' else -1.

    # 1. Create new path for ens0 from ens1's path
    ph_overlap0, op_overlap0, sh0 = cut_LR_to_M(ens1, reverse1)
    
    # For special case of [0^+-] primed ensemble, no propagation needed
    if ens0.ens_type == 'PPTIS_0plusmin_primed':
        new_path_0 = Path(ph_overlap0, op_overlap0, ens0.id)
        status0 = "ACC"   
    else:
        # Propagate to create complete path
        status0, tuple0 = propagate(ens0, sh0, reverse1,
                                  ens0.max_len - len(ph_overlap0))
    
    # If first propagation fails, return with error
    if status0 != "ACC":
        logger.info("First propagation was not succussful. Reason: {}".format(
            status0))
        if reverse1 == -1.:
            trial0 = Path(tuple0[0] + ph_overlap0, tuple0[1] + op_overlap0,
                        ens0.id)
        else:
            trial0 = Path(ph_overlap0 + tuple0[0], op_overlap0 + tuple0[1],
                        ens0.id)
        return status0, trial0, ens1.paths[0]

    # 2. Create new path for ens1 from ens0's path
    ph_overlap1, op_overlap1, sh1 = cut_LR_to_M(ens0, reverse0)
    
    # For special case of [N^+-] primed ensemble, no propagation needed
    if ens1.ens_type == 'PPTIS_Nplusmin_primed':
        new_path_1 = Path(ph_overlap1, op_overlap1, ens1.id)
        status1 = "ACC"
    else:
        # Propagate to create complete path
        status1, tuple1 = propagate(ens1, sh1, reverse0,
                                  ens1.max_len - len(ph_overlap1))
    
    # If second propagation fails, return with error
    if status1 != "ACC":
        logger.info("Second propagation was not succussful. Reason: {}".format(
            status1))
        if reverse0 == -1.:
            trial1 = Path(tuple1[0] + ph_overlap1, tuple1[1] + op_overlap1,
                        ens1.id)
        else:
            trial1 = Path(ph_overlap1 + tuple1[0], op_overlap1 + tuple1[1],
                        ens1.id)
        return status1, trial0, trial1

    # Construct complete paths from the propagated segments
    if ens0.ens_type != 'PPTIS_0plusmin_primed':
        if reverse1 == -1.:
            new_path_0 = Path(tuple0[0] + ph_overlap0, tuple0[1] + op_overlap0,
                            ens0.id)
        else:
            new_path_0 = Path(ph_overlap0 + tuple0[0], op_overlap0 + tuple0[1],
                            ens0.id)
            
    if ens1.ens_type != 'PPTIS_Nplusmin_primed':
        if reverse0 == -1.:
            new_path_1 = Path(tuple1[0] + ph_overlap1, tuple1[1] + op_overlap1,
                            ens1.id)
        else:
            new_path_1 = Path(ph_overlap1 + tuple1[0], op_overlap1 + tuple1[1],
                            ens1.id)
    
    # Final validation of both paths
    if not ens0.check_path(new_path_0):
        logger.warning("New path does not satisfy ensemble conditions.")
        return "NCR", new_path_0, new_path_1
        
    if not ens1.check_path(new_path_1):
        logger.warning("New path does not satisfy ensemble conditions.")
        return "NCR", new_path_0, new_path_1
        
    logger.debug("New paths are acceptable.")
    return "ACC", new_path_0, new_path_1

def kick_retis(ens):
    """Generates a completely new path for an ensemble by placing a new point
    near an interface and propagating backwards and forwards.
    
    This is used to initialize paths when no valid paths are available.
    The function repeatedly attempts to generate valid paths until successful.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble for which to generate a new path
        
    Returns
    -------
    None
        The function updates the ensemble with the new path directly
    """
    while True:
        # Create initial point based on dimension and ensemble type
        if ens.settings["dim"] == 1:
            # 1D case: position depends on ensemble ID
            if ens.id == 0:  # [0^-] ensemble
                # Slightly inside the state, from the right interface
                sh = (ens.intfs["R"]*(1 - np.sign(ens.intfs["R"])*0.02)-0.0001, 
                      ens.engine.draw_velocities())
            elif ens.id == 1:  # [0^+] ensemble
                # Slightly outside the state, from the left interface
                sh = (ens.intfs["L"]*(1 + np.sign(ens.intfs["L"])*0.02)+0.0001, 
                      ens.engine.draw_velocities())
            else:  # Other ensembles
                # Near the middle interface
                sh = (ens.intfs["M"]*(1 - np.sign(ens.intfs["M"])*0.2)-0.0001, 
                      ens.engine.draw_velocities())
        elif ens.settings["dim"] == 2:
            # 2D case: position depends on ensemble ID, adds orthogonal component
            orth_min = 0.
            orth_max = 0.3
            orth_coord = (orth_max-orth_min)*np.random.rand()+orth_min
            
            if ens.id == 0:  # [0^-] ensemble
                sh = (np.asarray([orth_coord, 
                                 ens.intfs["R"]*(1 - np.sign(ens.intfs["R"])*0.02)-0.0001]), 
                      ens.engine.draw_velocities())
            elif ens.id == 1:  # [0^+] ensemble
                sh = (np.asarray([orth_coord,
                                 ens.intfs["L"]*(1 + np.sign(ens.intfs["L"])*0.02)+0.0001]), 
                      ens.engine.draw_velocities())
            else:  # Other ensembles
                sh = (np.asarray([orth_coord,
                                 ens.intfs["M"]*(1 - np.sign(ens.intfs["M"])*0.02)-0.0001]), 
                      ens.engine.draw_velocities())
        
        # Calculate order parameter for the starting point
        shootpoint_op = ens.orderparameter.calculate(sh)
        logger.debug("Init from ph {} with op {}".format(sh, shootpoint_op))
        
        # Propagate backwards
        bw_status, bw_tuple = propagate(ens, sh, -1., ens.max_len-1)
        if bw_status != "ACC":
            continue  # Try again if backward propagation fails
        
        # Propagate forwards
        fw_status, fw_tuple = propagate(ens, sh, 1., 
                                      ens.max_len-len(bw_tuple[0]))
        if fw_status != "ACC":
            continue  # Try again if forward propagation fails
        
        # Create full path
        new_path = Path(bw_tuple[0] + [sh] + fw_tuple[0],
                      bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                      ens.id)
        
        # Check if path meets ensemble criteria
        if not ens.check_cross(new_path):
            continue  # Try again if path doesn't meet criteria
        else:
            break  # Success! Exit the loop
    
    # Add the new path to the ensemble
    ens.paths.append(new_path)
    ens.last_path = new_path
    ens.update_data("ACC", new_path, "ld", 0)
    
    return

def cut_LR_to_M(ens, reverse, level=0, M=None):
    """Cuts a path from the first or last phasepoint until the M interface is reached.
    
    This is a simplified version of cut_overlap_phasepoints, designed specifically
    for the REPPTIS swap move.
    
    Parameters
    ----------
    ens: :py:class:`Ensemble` object
        Ensemble whose path is cut
    reverse: float
        Propagation direction: forwards (1.) or backwards (-1.)
    level: int
        The level of the path to cut. Default is 0 (last accepted path).
    M: float or None
        The interface to cut to. If None, the M interface is set automatically
        based on the ensemble type.

    Returns
    -------
    phs: list of phasepoints
        The phasepoints in the overlap region
    ops: list of orderparameters
        The orderparameters in the overlap region
    shootpoint: phasepoint
        The phasepoint from which the propagation will start

    Notes
    -----
    - This function includes the shootpoint in the returned phasepoints
    - Cutting behavior for primed ensembles is specifically designed for the REPPTIS swap move
    """
    # Determine the interface to cut to based on ensemble type
    if ens.ens_type == 'PPTIS_0plusmin_primed':
        M = ens.intfs['L']
    elif ens.ens_type == 'PPTIS_Nplusmin_primed':
        M = ens.intfs['R']
    else:
        M = ens.intfs['M']

    if reverse == -1:
        # Extract shootpoint (first phasepoint)
        shootpoint = ens.paths[level].phasepoints[0]
        shootpoint_op = ens.paths[level].orders[0]
        
        # Determine if we're to the right or left of M interface
        right_of_M = True if shootpoint_op[0] > M else False
        
        # Start cutting from second point
        phs, ops = [], []
        for ph, op in zip(ens.paths[level].phasepoints[1:],
                          ens.paths[level].orders[1:]):
            phs.append(ph)
            ops.append(op)
            # Stop when we cross the M interface
            if right_of_M and op[0] < M:
                break
            elif not right_of_M and op[0] > M:
                break
                
        # Add the shootpoint at the beginning
        phs = [shootpoint] + phs
        ops = [shootpoint_op] + ops
        
    elif reverse == 1:
        # Extract shootpoint (last phasepoint)
        shootpoint = ens.paths[level].phasepoints[-1]
        shootpoint_op = ens.paths[level].orders[-1]
        
        # Determine if we're to the right or left of M interface
        right_of_M = True if shootpoint_op[0] > M else False
        
        # Start cutting from second-to-last point, going backward
        phs, ops = [], []
        for ph, op in zip(reversed(ens.paths[level].phasepoints[:-1]),
                          reversed(ens.paths[level].orders[:-1])):
            phs.append(ph)
            ops.append(op)
            # Stop when we cross the M interface
            if right_of_M and op[0] < M:
                break
            elif not right_of_M and op[0] > M:
                break
                
        # Re-reverse to maintain chronological ordering
        phs = phs[::-1]
        ops = ops[::-1]
        
        # Add the shootpoint at the end
        phs = phs + [shootpoint]
        ops = ops + [shootpoint_op]
    else:
        raise ValueError("reverse must be either 1 or -1")
    
    return phs, ops, shootpoint

def check_propagation_directions(ens0, ens1):
    """ Proposes propagation directions for the [i^+-] and [(i+1)^+-] paths, and
    checks whether this results in an acceptable swapping move.
    
    For a swap to be valid, the path directions need to be compatible with
    the path types (LMR, RMR, etc.) of the two ensembles.

    Parameters
    ----------
    ens0, ens1: :py:class:`Ensemble` objects
        The two ensembles whose paths are swapped

    Returns
    -------
    allowed: bool
        Whether the proposed move is allowed
    propdir0, propdir1: str
        The proposed propagation directions for the two paths ('forwards' or 'backwards')
    path0_type, path1_type: str
        The path types of the two paths (e.g., 'LMR', 'RML')

    """
    # Check the position of the start and end points of the two paths
    start0_pos, end0_pos = ens0.check_start_end_positions(ens0.paths[0])
    start1_pos, end1_pos = ens1.check_start_end_positions(ens1.paths[0])
    
    # Determine the path types
    p0type = start0_pos + "M" + end0_pos
    p1type = start1_pos + "M" + end1_pos
    
    # Randomly select propagation directions
    propdir0 = ['backwards', 'forwards'][round(np.random.rand())]
    propdir1 = ['backwards', 'forwards'][round(np.random.rand())]

    # Define rules for allowed propagation directions
    allow = {
        'leftright': {'L': False, 'R': True},  # For LMR paths
        'rightleft': {'L': True, 'R': False}   # For RML paths
    }
    
    # Check if proposed directions are compatible with path types
    allowed0 = allow['leftright'][start0_pos if propdir0 == 'backwards' else end0_pos]
    allowed1 = allow['rightleft'][start1_pos if propdir1 == 'backwards' else end1_pos]
    allowed = allowed0 and allowed1
    
    # Additional constraints for primed ensembles
    allowed2 = True
    if ens0.ens_type == 'PPTIS_0plusmin_primed':
        allowed2 = propdir1 == 'backwards'
    if ens1.ens_type == 'PPTIS_Nplusmin_primed':
        allowed2 = propdir0 == 'backwards'
    
    # Combined allowance check
    allowed = allowed and allowed2

    # Log detailed information about the proposed swap
    msg = "Proposed swap move:\n"
    msg+= f"{ens0.name} ({ens0.id}) <--> {ens1.name} ({ens1.id})\n"
    msg+= f"Proposed directions: {propdir0} <-> {propdir1}\n"
    msg+= f"Path types: {p0type} <-> {p1type}"
    logger.info(msg)

    return allowed, propdir0, propdir1, p0type, p1type

def propagate(ens, sh, reverse, maxlen):
    """Propagate from a phasepoint in a specified direction until termination conditions are met.
    
    The function propagates a trajectory from the shooting point until either:
    1. A crossing condition is satisfied (path reaches an "extremal condition")
    2. The maximum path length is reached
    3. The path crosses an interface that violates ensemble constraints
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble to propagate in
    sh : phasepoint 
        Phasepoint to propagate from (tuple (x,v))
    reverse : float 
        Direction: forwards (1.) or backwards (-1.)
    maxlen : int
        Maximum length of the path to generate

    Returns
    -------
    status : str
        Status of the propagation:
        - "ACC": Accepted (successful propagation)
        - "BWI"/"FWI": Backward/Forward wrong interface
        - "BTL"/"FTL": Backward/Forward too long
    trial_tuple : tuple
        Tuple of (phasepoints, orderparams, ensemble_id)

    Notes
    -----
    The returned path does NOT include the shooting point!
    """
    # Set up conditions based on propagation direction
    if reverse == -1:
        logger.debug("Propagating backwards")
        conds = {
            "cond": ens.start_conditions,
            "rej_intf": "BWI",  # Backward wrong interface
            "rej_maxlen": "BTL", # Backward too long
            "type_cond": "start"
        }
    elif reverse == 1:
        logger.debug("Propagating forwards")
        conds = {
            "cond": ens.end_conditions,
            "rej_intf": "FWI",  # Forward wrong interface
            "rej_maxlen": "FTL", # Forward too long
            "type_cond": "end"
        }
    else:
        raise ValueError("reverse must be either 1 or -1")

    # Uncomment for visualization of trajectory (debugging)
    # fig, ax = plt.subplots()
    # lines, = ax.plot([],[])
    # ax.set_autoscaley_on(True)
    # ax.set_ylim(-0.2, 0.4)

    phs, ops = [], []
    run_len = 0
    run_worthy = True
    
    # Reverse velocities for backward propagation
    ph = (sh[0], reverse*sh[1])
    
    while run_worthy:
        # Visualization code (uncomment for debugging)
        # if run_len % 10000 == 0:
        #     print("step: ", run_len)
        #     lines.set_ydata(ops[0 if len(ops)<150000 else -150000::100])
        #     lines.set_xdata([i for i in range(len(ops[0 if len(ops)<150000 else -150000::100]))])
        #     ax.relim()
        #     ax.autoscale_view()
        #     fig.canvas.draw()
        #     fig.canvas.flush_events()
        
        # Propagate one step
        ph = ens.engine.step(ph)
        op = ens.orderparameter.calculate(ph)
        
        # Store phasepoint (with reversed velocity if going backwards)
        phs.append((ph[0], reverse*ph[1]))
        ops.append(op)
        
        # Check position relative to interfaces
        LR_pos = check_position(op, ens.intfs['L'], ens.intfs['R'])
        run_len += 1
        
        # Check if we've hit an extremal condition
        if LR_pos in ens.extremal_conditions:
            run_worthy = False
            
            # Check if the condition is compatible with our direction
            if LR_pos in conds['cond']:
                msg = f"Path crossed {LR_pos}, which is part of the "
                msg += f"{conds['type_cond']} conditions {conds['cond']}."
                logger.debug(msg)
                status = "ACC"
            else:
                msg = f"Path crossed {LR_pos}, which is not part of the "
                msg += f"{conds['type_cond']} conditions {conds['cond']}."
                logger.debug(msg)
                status = conds['rej_intf']
                
        # Check if we've exceeded max length
        if run_len >= maxlen:
            logger.debug(f"Path too long ({run_len} >= {maxlen}).")
            status = conds['rej_maxlen']
            run_worthy = False
    
    # For backward propagation, we need to reverse the order of phasepoints
    if reverse == -1:
        trial_tuple = (phs[::-1], ops[::-1], ens.id)
    else:
        trial_tuple = (phs, ops, ens.id)

    return status, trial_tuple

def cut_extremal_phasepoints(ens, reverse, level=0):
    """Cuts and returns the two first or last phasepoints of a path.
    
    This function extracts the endpoints of a path that will serve as the 
    starting point for extending into another ensemble during swaps.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble containing the path to cut
    reverse : float
        Direction indicator: forwards (1, cut last two phasepoints) or 
        backwards (-1, cut first two phasepoints)
    level : int
        Level of the path to cut (0 = last accepted path)

    Returns
    -------
    ph_overlap : list of phasepoints
        List of the two phasepoints
    op_overlap : list of floats
        List of the two order parameters
    sh : phasepoint
        Shooting point to generate the new path
    """
    if reverse == -1:
        # Cut first two points (for backward propagation)
        ph_overlap = [ens.paths[level].phasepoints[i] for i in [0, 1]]
        op_overlap = [ens.paths[level].orders[i] for i in [0, 1]]
        sh = ens.paths[level].phasepoints[0]  # First point is shooting point
    elif reverse == 1:
        # Cut last two points (for forward propagation)
        ph_overlap = [ens.paths[level].phasepoints[i] for i in [-2, -1]]
        op_overlap = [ens.paths[level].orders[i] for i in [-2, -1]]
        sh = ens.paths[level].phasepoints[-1]  # Last point is shooting point
    else:
        raise ValueError("reverse must be either 1 or -1")
    return ph_overlap, op_overlap, sh

def num_shootpoints(orders, l, r):
    """Counts the number of points in a trajectory that lie between two interfaces.
    
    Parameters
    ----------
    orders : list
        List of order parameters along the trajectory
    l : float
        Left (lower) interface value
    r : float
        Right (upper) interface value
        
    Returns
    -------
    int
        Number of points between the interfaces (inclusive)
    """
    ops = np.array(orders)
    return np.count_nonzero(np.logical_and(ops >= l, ops <= r))


# Legacy functions are kept below for backward compatibility
# These are retained but not documented as they are superseded by more optimized versions above

###############################################################################
# OLD FUNCTIONS
###############################################################################
def repptis_swap_old(ensembles, idx):
    """ Performs a swapping move in REPPTIS simulations, between adjacent
    PPTIS ensembles. First, propagation directions are randomly chosen for both
    paths, and it is checked whether the pathtypes (i.e. LMR, RMR, ...) are
    compatible. If not, the move is rejected. If the proposed directions are
    compatible with the pathtypes, then the path segments in the overalapping
    region are cut, and they are propagated in the proposed directions.

    For compatible propagation directions, the paths are created as follows:
    1) new [i^+-] path from old [(i+1)^+-] path. The path segment in the 'LM'
    region is cut out of the old [(i+1)^+-] path (with one point left of the
    L interface, and one point right of the M interface). This path segment is
    then extended by propagating the phasepoint left of the L interface in the
    proposed direction until a crossing condition of the [i^+-] inteface occurs.

    2) new [(i+1)^+-] path from old [i^+-] path. The path segment in the 'MR'
    region is cut out of the old [i^+-] path (with one point left of the M
    interface, and one point right of the R interface). This path segment is
    then extended by propagating the phasepoint right of the R interface in the
    proposed direction until a crossing condition of the [(i+1)^+-] inteface
    occurs.

    Note about overlap_part:
        Standard behaviour is to include the shootpoint, otherwise it may
        change be recalculating the orderparamater, and create potential
        problems by shifting position along an interface.
    
    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of ensembles present in the simulation
    idx: int
        The index of the ensemble whose path is swapped with the path of the
        next ensemble in the list

    """
    logger.info("Swapping: {} <-> {}".format(idx, idx+1))
    # if idx == 0, we perform a swap_zero move
    if idx == 0:
        return swap_zero(ensembles)
    # Else, we do the repptis swap. This is very similar to the swap_zero move,
    # but we have to be careful about the path types.
    ens0, ens1 = ensembles[idx], ensembles[idx+1]
    # Choose propagation directions for the two paths, and check if the proposed
    # move is allowed or not
    allowed, propdir0, propdir1, path0_type, path1_type = \
        check_propagation_directions(ens0, ens1)
    if not allowed:
        msg = "Proposed move is not allowed. Incompatible path types and "
        msg += "propagation directions."
        logger.debug(msg)
        return 'SWD', ens0.paths[0], ens1.paths[0]  # Swap Wrong Direction

    # If allowed, the swap move is attempted
    msg = "Attempting swap of {} and {} paths with propdirs {} and {}."
    logger.debug(msg.format(path0_type, path1_type, propdir0, propdir1))

    # First create path0_new, then path1_new.
    # We will immediately reject the move if path0_new is not valid.

    # 1) new [i^+-] path from old [(i+1)^+-] path
    ph_overlap0, op_overlap0, sh0 = \
        cut_overlap_phasepoints(ens1, propdir1, side='right')
    # now we can propagate the phasepoint sh0 in the proposed direction
    if ens0.ens_type == 'PPTIS_0plusmin_primed':  # Automatically acceptable
        new_path_0 = Path(ph_overlap0, op_overlap0, ens0.id)
        status0 = "ACC"   
    else:
        ph_extend0, op_extend0 = [], []
        run_len = len(ph_overlap0)
        crossed = False
        run_worthy = True
        reverser0 = 1. if propdir1 == 'forwards' else -1.
        ph = (sh0[0], reverser0*sh0[1])
        while run_worthy:
            ph = ens0.engine.step(ph)
            op = ens0.orderparameter.calculate(ph)
            ph_extend0.append((ph[0], reverser0*ph[1]))
            op_extend0.append(op)
            run_len += 1
            LR_pos = check_position(op, ens0.intfs['L'], ens0.intfs['R'])
            if LR_pos in ['L', 'R']:
                run_worthy = False
                if LR_pos in ens0.end_conditions if reverser0 == 1. else \
                        ens0.start_conditions:
                    msg = f"Path crossed {LR_pos}, which is part of the"
                    msg+= "{}".format("end" if reverser0 == 1. else "start")
                    msg+= " conditions {}".format(ens0.end_conditions if \
                                reverser0 == 1. else ens0.start_conditions)
                    logger.debug(msg)
                    crossed = True
                    status0 = "ACC"
                else:
                    msg = f"Path crossed {LR_pos}, which is not part of the"
                    msg+= "{}".format("end" if reverser0 == 1. else "start")
                    msg+= " conditions {}".format(ens0.end_conditions if \
                                reverser0 == 1. else ens0.start_conditions)
                    logger.debug(msg)
                    logger.debug("Path hit the wrong interface.")
                    status0 = "FWI" if reverser0 == 1. else "BWI"
            if run_len >= ens0.max_len and not crossed:
                logger.debug(f"Path too long ({run_len} >= {ens0.max_len})")
                status0 = "FTL" if reverser0 == 1. else "BTL"

    if status0 != "ACC":
        logger.info("First propagation was not succussful. Reason: {}".format(
            status0))
        if reverser0 == -1.:
            trial0 = Path(ph_extend0[::-1] + ph_overlap0,
                          op_extend0[::-1] + op_overlap0,
                          ens0.id)
        else:
            trial0 = Path(ph_overlap0 + ph_extend0,
                          op_overlap0 + op_extend0,
                          ens0.id)
        return status0, trial0, ens1.paths[0]

    # 2) new [(i+1)^+-] path from old [i^+-] path
    ph_overlap1, op_overlap1, sh1 = \
        cut_overlap_phasepoints(ens0, propdir0, side='left')
    # now we can propagate the phasepoint sh1 in the proposed direction
    run_len = len(ph_overlap1)
    crossed = False
    run_worthy = True
    reverser1 = 1. if propdir0 == 'forwards' else -1.
    ph = (sh1[0], reverser1*sh1[1])
    ph_extend1, op_extend1 = [], []
    while run_worthy:
        ph = ens1.engine.step(ph)
        op = ens1.orderparameter.calculate(ph)
        ph_extend1.append((ph[0], reverser1*ph[1]))
        op_extend1.append(op)
        run_len += 1
        LR_pos = check_position(op, ens1.intfs['L'], ens1.intfs['R'])
        if LR_pos in ['L', 'R']:
            run_worthy = False
            if LR_pos in ens1.end_conditions if reverser1 == 1. else \
                    ens1.start_conditions:
                msg = f"Path crossed {LR_pos}, which is part of the"
                msg+= "{}".format("end" if reverser1 == 1. else "start")
                msg+= " conditions {}".format(ens1.end_conditions if \
                            reverser1 == 1. else ens1.start_conditions)
                logger.debug(msg)
                crossed = True
                status1 = "ACC"
            else:
                msg = f"Path crossed {LR_pos}, which is not part of the"
                msg+= "{}".format("end" if reverser1 == 1. else "start")
                msg+= " conditions {}".format(ens1.end_conditions if \
                            reverser1 == 1. else ens1.start_conditions)
                logger.debug(msg)
                logger.debug("Path hit the wrong interface.")
                status1 = "FWI" if reverser1 == 1. else "BWI"
        if run_len >= ens1.max_len and not crossed:
            logger.debug(f"Path too long ({run_len} >= {ens1.max_len})")
            status1 = "FTL" if reverser1 == 1. else "BTL"

    if status1 != "ACC":
        logger.info("Second propagation was not succussful. Reason: {}".format(
            status1))
        if reverser1 == -1.:
            trial1 = Path(ph_extend1[::-1] + ph_overlap1,
                          op_extend1[::-1] + op_overlap1,
                          ens1.id)
        else:
            trial1 = Path(ph_overlap1 + ph_extend1,
                          op_overlap1 + op_extend1,
                          ens1.id)
        return status1, trial0, trial1

    # If we reached this point, we have two new paths. We now check whether they
    # satisfy the crossing conditions.
    if reverser0 == -1.:
        new_path_0 = Path(ph_extend0[::-1] + ph_overlap0,
                          op_extend0[::-1] + op_overlap0,
                          ens0.id)
    else:
        new_path_0 = Path(ph_overlap0 + ph_extend0,
                          op_overlap0 + op_extend0,
                          ens0.id)
    if reverser1 == -1.:
        new_path_1 = Path(ph_extend1[::-1] + ph_overlap1,
                          op_extend1[::-1] + op_overlap1,
                          ens1.id)
    else:
        new_path_1 = Path(ph_overlap1 + ph_extend1,
                          op_overlap1 + op_extend1,
                          ens1.id)

    if not ens0.check_path(new_path_0):
        logger.warning("New path does not satisfy ensemble conditions.")
        return "NCR", new_path_0, new_path_1
    if not ens1.check_cross(new_path_1):
        logger.warning("New path does not satisfy ensemble conditions.")
        return "NCR", new_path_0, new_path_1
    else:
        logger.debug("New paths are acceptable.")
        return "ACC", new_path_0, new_path_1
    
def cut_overlap_phasepoints(ens, propdir, side, level=0):
    """ Cut the phasepoints in the overlapping region of two PPTIS ensembles.

    Parameters
    ----------
    ens: :py:class:`Ensemble` object
        Ensemble whose path is cut
    propdir: str
        Propagation direction of the path. Forwards or backwards
    side: string
        This is either 'left' or 'right', and denotes the side from which
        the path originates. left: [i^+-] path to be propagated into [i+1^+-],
        right: [(i+1)^+-] path to be propagated into [i^+-].
        
    Returns
    -------
    phasepoints_overlap : list of phasepoints
        The phasepoints in the overlap region
    shootpoint : phasepoint
        The phasepoint from which the propagation will start.

    Notes
    -----
    Note that here we need to re-reverse paths that are reversed,
    as we are not using the 'paste-paths' function from pyretis...

    Note that this function assumes that the proposed combination of 
    propdir and side makes sense for ens.last_path...

    """
    # intf_M defines when to stop cutting phasepoints, starting from a L or R
    # interface. For now, this only differs from M in the case of a [0^+-']
    if ens.ens_type == 'PPTIS_0plusmin_primed':
        intf_M = ens.intfs['L']
    elif ens.ens_type == 'PPTIS_Nplusmin_primed':
        intf_M = ens.intfs['R']
    else:
        intf_M = ens.intfs['M']

    phasepoints_overlap = []
    orders_overlap = []
    include_shootpoint = True  # standard behaviour

    if side == 'right':
        if propdir == 'backwards':
            shoot_point = ens.paths[level].phasepoints[0]
            if include_shootpoint:
                phasepoints_overlap.append(shoot_point)
                orders_overlap.append(ens.paths[level].orders[0])
            phase_points = ens.paths[level].phasepoints[1:]
            orders = ens.paths[level].orders[1:]
            for phase_point, order in zip(phase_points, orders):
                phasepoints_overlap.append(phase_point)
                orders_overlap.append(order)
                if order[0] > intf_M:  # if > M, we stop cutting
                    break
        elif propdir == 'forwards':
            shoot_point = ens.paths[level].phasepoints[-1]
            if include_shootpoint:
                phasepoints_overlap.append(shoot_point)
                orders_overlap.append(ens.paths[level].orders[-1])
            phase_points = ens.paths[level].phasepoints[:-1]
            orders = ens.paths[level].orders[:-1]
            for phase_point, order in zip(reversed(phase_points),
                                          reversed(orders)):
                phasepoints_overlap.append(phase_point)
                orders_overlap.append(order)
                if order[0] > intf_M:
                    break
            # re-reverse the phasepoints and orders
            phasepoints_overlap = phasepoints_overlap[::-1]
            orders_overlap = orders_overlap[::-1]
    elif side == 'left':
        if propdir == 'backwards':
            shoot_point = ens.paths[level].phasepoints[0]
            if include_shootpoint:
                phasepoints_overlap.append(shoot_point)
                orders_overlap.append(ens.paths[level].orders[0])
            phase_points = ens.paths[level].phasepoints[1:]
            orders = ens.paths[level].orders[1:]
            for phase_point, order in zip(phase_points, orders):
                phasepoints_overlap.append(phase_point)
                orders_overlap.append(order)
                if order[0] < intf_M:
                    break
        elif propdir == 'forwards':
            shoot_point = ens.paths[level].phasepoints[-1]
            if include_shootpoint:
                phasepoints_overlap.append(shoot_point)
                orders_overlap.append(ens.paths[level].orders[-1])
            phase_points = ens.paths[level].phasepoints[:-1]
            orders = ens.paths[level].orders[:-1]
            for phase_point, order in zip(reversed(phase_points),
                                          reversed(orders)):
                phasepoints_overlap.append(phase_point)
                orders_overlap.append(order)
                if order[0] < intf_M:
                    break
            # re-reverse the phasepoints and orders
            phasepoints_overlap = phasepoints_overlap[::-1]
            orders_overlap = orders_overlap[::-1]
    return phasepoints_overlap, orders_overlap, shoot_point