import numpy as np
import logging
import matplotlib.pyplot as plt

from funcs import plot_paths, check_position, validate_staple
from path import Path
from moves import propagate, cut_extremal_phasepoints
from order import OrderParameter

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

def pg_shooting_move(ens, level=0):
    """ Performs a shooting move in an [i*] ensemble.

    A shooting move attempts to generate a new path by selecting a random phasepoint 
    (the "shootpoint") from the current path, assigning new velocities, and propagating 
    both backward and forward in time from this point.
    
    In an [i*] ensemble, the shootpoint is chosen from the REPPTIS region between 
    interfaces i-1 and i+1 of the last accepted path in the ensemble. The shootpoint 
    is given new velocities drawn from the Maxwell-Boltzmann distribution. A new path 
    is generated by propagating the shootpoint backwards and forwards in time, with 
    backwards propagation achieved by reversing the shootpoint's velocities.

    To maintain detailed balance, the new path is accepted with probability
    min(1, len(old_path)/len(new_path)). For computational efficiency, we draw a random
    number between 0 and 1 and propagate the new_path until len(old_path)/Q.

    The generated path is then verified to ensure it satisfies all the required 
    acceptance conditions for the ensemble.

    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble in which the shooting move is performed
    level : int
        The level of the path to shoot from in ensemble ens. Default is 0,
        which refers to the most recently accepted path.

    Returns
    -------
    success : string
        String indicating whether the shooting move was successful ("ACC" for accepted,
        or various error codes like "NCR", "BTL", "FTL", "ILL" for different rejection reasons)
    new_path : :py:class:`Path` object or tuple
        New path generated by the shooting move, or a tuple containing the path and its type
        when extension was performed

    Notes
    -----
    For [i*] ensembles, the shooting procedure includes extending the path beyond the 
    transition region when necessary to ensure proper sampling of the ensemble space.
    """
    path = ens.paths[level]  # Get the last accepted path at specified level
    pathlen = len(path.phasepoints)

    # Select eligible shooting points based on ensemble type
    if ens.ens_type == "i*_0star":
        # For i*_0star ensembles, select points in the region between specified interfaces
        # and within the star region indicated by staridx bounds
        poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["all"][0] and 
                                               path.orders[i][0] <= ens.intfs["all"][1] and 
                                               i >= path.staridx[0] and 
                                               i <= path.staridx[1])]
    else:
        # For other i* ensembles, select points between L and R interfaces within the star region
        poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["L"] and 
                                               path.orders[i][0] <= ens.intfs["R"] and 
                                               i >= path.staridx[0] and 
                                               i <= path.staridx[1])]
    
    n_ph = len(poss_sh)
    if n_ph == 0:
        # Handle the case where no eligible shooting points are found
        n_ph = 0
        print(f"No eligible shooting points found in ensemble {ens.id}")
        print(f"Path: {path.orders}")
    
    # Randomly select one of the possible shooting points
    sh_id = np.random.choice(poss_sh)

    # Create shooting point with new velocities but preserve position
    shootpoint = (path.phasepoints[sh_id][0],
                  ens.engine.draw_velocities())
    
    # Calculate maximum path length based on acceptance probability and ensemble limits
    shoot_maxlen = min(int(n_ph/np.random.rand()) + 2, ens.max_len)
    # We will not recalculate the orderparameter for this phasepoint, as 
    # external engines may save phasepoints at a lower precision. This can
    # lead to the recalculated phasepoint shifting position w.r.t. an interface,
    # resulting in all sorts of nasty problems.
    # shootpoint_op = ens.orderparameter.calculate(shootpoint)
    shootpoint_op = path.orders[sh_id]      # = list with 1D op at index 0 and orthogonal op at other indices    
    logger.debug("Shooting from ph {} (idx: {}) with op {}".format(
        shootpoint, sh_id, shootpoint_op))
    # We now start propagating the shootpoint backwards first, because often
    # the backwards part (corresponding to the starting condition) is more
    # restrictive than the forwards part (corresponding to the end condition).
    # propagate backwards. Maxlen = shoot_maxlen-1, because shootpoint is 1
    bw_status, bw_tuple = propagate(ens, shootpoint, -1., shoot_maxlen-2) # -1 because shootpoint not incl
    # if unsuccessful, return the status and the partially propagated path
    if bw_status != "ACC": 
        logger.debug("Backwards propagation not successful: {}".format(
            bw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0]+[shootpoint], bw_tuple[1]+[shootpoint_op], ens.id))
        return bw_status, Path(bw_tuple[0]+[shootpoint],
                               bw_tuple[1]+[shootpoint_op],
                               ens.id, [ptype, 0, bw_status, shootpoint_op])
    
    # If backwards propagation succeeds, continue with forwards propagation
    # Adjust maxlen to account for already generated backwards path
    fw_status, fw_tuple = propagate(ens, shootpoint, 1.,
                                    shoot_maxlen-len(bw_tuple[0])-1)
    
    # If forwards propagation fails, return with partial path and status
    if fw_status != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(
            fw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id))
        return fw_status, Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id, [ptype, 0, fw_status, shootpoint_op])
    
    # If both propagations succeed, create the full new path and determine its type
    ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id))
    new_path = Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id, [ptype, 0, shootpoint_op])
    
    # Check for illegal path types (relevant for primed ensembles)
    ptype = ens.get_ptype(new_path)
    if ptype in ens.illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype))
        new_path.meta = [ptype, 0, "ILL", shootpoint_op]
        return "ILL", new_path
    
    # Check if the new path satisfies the crossing conditions
    if not ens.check_cross(new_path):
        logger.debug("New path does not satisfy ensemble crossing conditions")
        new_path.meta = [ptype, 0, "NCR", shootpoint_op]
        return "NCR", new_path
    
    # Handle special path types that require extension
    if ptype == "RMR" or ptype == "LML":
        # For reflexive paths (RMR or LML), extend in one direction from an endpoint
        prop_idx = np.random.choice([0, -1])  # Choose which endpoint to extend from
        rev = -np.sign(prop_idx+0.5)  # Determine propagation direction (-1 or 1)
        prop_point = new_path.phasepoints[prop_idx]  # Get the endpoint phasepoint
        
        # Extend the path from the chosen endpoint
        ext_status, ext_tuple = ext_propagate(ens, prop_point, 
                                            rev, ens.max_len-len(new_path.orders))
        
        # Create extended path based on propagation direction
        if rev == -1:
            # Extending backwards (prepend new points)
            ext_path = Path(ext_tuple[0] + new_path.phasepoints,
                            ext_tuple[1] + new_path.orders,
                            ens.id, [ptype, 1 if ptype=="LML" else -1, shootpoint_op])
            li = len(ext_tuple[1])+1
            ri = len(ext_path.orders)-2
        else:
            # Extending forwards (append new points)
            ext_path = Path(new_path.phasepoints + ext_tuple[0],
                            new_path.orders + ext_tuple[1],
                            ens.id, [ptype, -1 if ptype=="LML" else 1, shootpoint_op])
            li = 1
            ri = len(new_path.orders)-2
        
        # Check if extension was successful
        if ext_status != "ACC":
            logger.debug("Half extension not successful: {}".format(
                ext_status))
            ext_path.meta = [ptype, 0, ext_status, shootpoint_op]
            return ext_status, (ext_path, ptype)
        else:
            # Extension successful, set star region indices and return
            ext_path.staridx = (int(li), int(ri))
            logger.debug("Extension performed successfully.")
            ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
            return "ACC", (ext_path, ptype)
    else:
        # For non-reflexive paths (LMR, RML), extend in both directions
        # First extend backwards
        bext_status, bext_tuple = ext_propagate(ens, new_path.phasepoints[0], -1., ens.max_len-len(new_path.orders))
        
        # Check if backwards extension was successful
        if bext_status != "ACC": 
            logger.debug("Backwards extension not successful: {}".format(
                bext_status))
            return bext_status, (Path(bext_tuple[0]+new_path.phasepoints,
                                bext_tuple[1]+new_path.orders,
                                ens.id, [ptype, 0, bext_status, shootpoint_op]), ptype)
        
        # If successful, continue with forwards extension
        fext_status, fext_tuple = ext_propagate(ens, new_path.phasepoints[-1], 1.,
                                ens.max_len-len(bext_tuple[0])-len(new_path.orders))
        
        # Check if forwards extension was successful
        if fext_status != "ACC":
            logger.debug("Forwards extension not successful: {}".format(
                fext_status))
            return fext_status, (Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                bext_tuple[1] + new_path.orders + fext_tuple[1],
                                ens.id, [ptype, 0, fext_status, shootpoint_op]), ptype)
        else:
            # Both extensions successful, create final path and set star region indices
            logger.debug("Extension performed successfully.")
            ext_path = Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                bext_tuple[1] + new_path.orders + fext_tuple[1],
                                ens.id, [ptype, 0, "ACC", shootpoint_op])
            
            # Set the star region indices to track the transition region
            ext_path.staridx = (len(bext_tuple[1])+1, len(bext_tuple[1]) + len(new_path.orders)-2)
            return "ACC", (ext_path, ptype)

def pg_swap_zero(ensembles):
    """ Performs a swap move between the [0^-] (or [0^-']) and [0^*] (or [0^*'])
    ensembles, integrating new trajectory segments as needed.

    This specialized swap move handles the exchange between paths at the leftmost boundary
    of the interface set. The path from the [0^-] ensemble is extended into the [0^*] ensemble 
    by propagating the last path forwards in time, keeping the last two phasepoints and 
    extending from there. Similarly, the path of the [0^*] ensemble is extended into the [0^-] 
    ensemble by propagating backwards in time, keeping the first two phasepoints and
    extending from there.

    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of two ensembles between which the swap is performed (typically [0^-] and [0^*])

    Returns
    -------
    success : string
        String indicating whether the swap move was successful ("ACC" for accepted,
        or various error codes for different rejection reasons)
    new_path_0m : :py:class:`Path` object
        New path of the [0^-] ensemble after the swap
    new_path_0star : :py:class:`Path` object
        New path of the [0^*] ensemble after the swap

    Notes
    -----
    This function is specifically designed for the interface between stable state A
    and the transition region. It requires full integration of new path segments
    rather than a simple exchange of paths.
    """
    ens0, ens1 = ensembles[0], ensembles[1]
    # 1. create the new path for the [0^+] ensemble.
    # Cut the last two phasepoints of the [0^-] path, and propagate the last
    # phasepoint forwards in time. Remember, the shoot phasepoint is already
    # present in ph1 and op1 via cut_extremal_phasepoints.
    ph1, op1, sh1 = cut_extremal_phasepoints(ens0, 1.)
    if op1[-1][0] <= ens0.intfs["L"] or op1[-1][0] >= ens0.intfs["R"]:
        logger.debug("Swap not allowed")
        return "SWD", ens0.paths[0], ens1.paths[0]
    status1, tuple1 = propagate(ens1, sh1, 1., ens1.max_len - 2)
    # If not successful, return the status and the partially propagated path
    if status1 != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(status1))
        return status1, ens0.paths[0], (Path(ph1 + tuple1[0],
                                            op1 + tuple1[1],
                                            ens1.id))
    # If successful, the new path should satisfy the crossing conditions.
    new_path1 = Path(ph1 + tuple1[0], op1 + tuple1[1], ens1.id)
    ptype1 = ens1.get_ptype(new_path1)

    if not ens1.check_cross(new_path1):
        logger.warning("New path [0^+] doesn't satisfy ens cross conditions")
        return "NCR", ens1.paths[0], new_path1
    if ptype1 != "LML":
        ext_status, ext_tuple = ext_propagate(ens1, new_path1.phasepoints[-1], 1.,
                                ens1.max_len-len(new_path1.orders))
        if ext_status != "ACC":
            logger.debug("Forwards extension in [0^*] not successful: {}".format(
                ext_status))
            return ext_status, ens1.paths[0], (Path(ph1 + tuple1[0] + ext_tuple[0],
                                            op1 + tuple1[1] + ext_tuple[1],
                                            ens1.id), [ptype1, 0, ext_status, sh1[0]])
        if new_path1.orders[-1][0] <= ens1.intfs["L"]:
            ptype1 = "LML"
        new_path1 = Path(ph1 + tuple1[0] + ext_tuple[0], op1 + tuple1[1] + ext_tuple[1], ens1.id, 
                         [ptype1, 0, ext_status, sh1[0]])
    else:
        new_path1.meta = [ptype1, 0, "ACC", op1[-1]]

    valid1, ptype1 = pg_check_path(ens1, new_path1)
    if not valid1:
        logger.warning("New path in [0^*] doesn't satisfy ens check conditions")
        return "NCR", ens1.paths[0], (new_path1, ptype1)

    new_path1.staridx = (1, len(tuple1[1]))
    if ptype1 in ens1.illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype1))
        new_path1.meta = [ptype1, 0, "ILL", op1[-1]]
        return "ILL", ens0.paths[0], (new_path1, ptype1)
    
    # 2. create the new path for the [0^-] ensemble.
    # Cut the first two phasepoints of the [0^+] path, and propagate the first
    # phasepoint backwards in time. Remember, the shoot phasepoint is already
    # present in ph0 and op0 via cut_extremal_phasepoints.
    ph0, op0, sh0 = cut_extremal_phasepoints(ens1, -1.)
    if op0[0][0] >= ens1.intfs["R"] or op0[1][0] >= ens1.intfs["R"]:
        logger.debug("Swap not allowed")
        return "SWD", ens0.paths[0], new_path1
    status0, tuple0 = propagate(ens0, sh0, -1., ens0.max_len - 2)
    # If not successful, return the status and the partially propagated path
    if status0 != "ACC":
        logger.debug("Backwards propagation not successful: {}".format(status0))
        return status0, Path(tuple0[0] + ph0, tuple0[1] + op0, ens0.id),\
            new_path1
    # If successful, the new path should satisfy the crossing conditions.
    new_path0 = Path(tuple0[0] + ph0, tuple0[1] + op0, ens0.id)
    ptype0 = ens0.get_ptype(new_path0)
    if not ens0.check_cross(new_path0):
        logger.warning("New path [0^-] doesn't satisfy ens cross conditions")
        return "NCR", new_path0, new_path1
    # If we reached this point, both new paths have been double checked, and we
    # return the accepted paths.
    return "ACC", (new_path0, ptype0), (new_path1, ptype1)


def pg_swap(ensembles, idx):
    """ Performs a swap move between the last paths of two ensembles from an [i*] simulation.

    This function attempts to exchange paths between adjacent ensembles in the replica 
    exchange scheme. Unlike regular replica exchange which simply swaps configurations, 
    this function verifies that each path meets the criteria of its new ensemble.
    
    The function checks whether the path of ensembles[idx] satisfies the crossing conditions
    of ensembles[idx+1] and vice versa. If both paths meet the criteria of their new
    ensembles, the swap is accepted.

    Parameters
    ----------
    ensembles: list of :py:class:`Ensemble` objects
        List of ensembles present in the simulation
    idx: int
        Index of the ensemble to swap with the next ensemble in the list (ensembles[idx+1])

    Returns
    -------
    success : string
        String indicating whether the swap move was successful ("ACC" for accepted, 
        "NCR" or "ILL" for rejection)
    path_tuple1 : tuple
        Tuple containing the path for the first ensemble and its type
    path_tuple2 : tuple
        Tuple containing the path for the second ensemble and its type
        
    Notes
    -----
    Special handling is implemented for reflexive path types (RMR, LML) which have 
    specific requirements for valid exchange.
    """
    lower_path = ensembles[idx].paths[0]
    upper_path = ensembles[idx+1].paths[0]
    if upper_path.meta[0] == "RMR" or lower_path.meta[0] == "LML":
        return "NCR", (upper_path, "***"), (lower_path, "***")
    is_path1, ptype1 = pg_check_path(ensembles[idx+1], lower_path)
    is_path2, ptype2 = pg_check_path(ensembles[idx], upper_path) 
    if ptype1 in ensembles[idx+1].illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype1))
        return "ILL", (lower_path, ptype1), (upper_path, ptype2)
    if ptype2 in ensembles[idx].illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype2))
        return "ILL", (lower_path, ptype1), (upper_path, ptype2)
    # plot_paths([lower_path])
    # plot_paths([upper_path])
    # Only proceed if both paths are valid for their target ensembles
    if is_path1 and is_path2:
        try:
            #-----------------------------------------------------------------
            # PART 1: Calculate valid star region indices for lower path
            # when moved to the upper ensemble (idx+1)
            #-----------------------------------------------------------------
            
            # Determine star region based on path type and characteristics
            if lower_path.staridx[0] == 1 and lower_path.staridx[1] == len(lower_path.orders)-1:
                # Full path case (entire path is in star region)
                # Find first valid point outside interface region, going backward from end
                idx1l = next(i for i in range(lower_path.staridx[1], -1, -1) 
                    if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") + 1
                # Find first valid point outside interface region, going forward from end
                idx1r = next(i for i in range(lower_path.staridx[1], len(lower_path.orders)) 
                    if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
            
            elif lower_path.meta[0] == "RMR":  # Special handling for right-middle-right paths
                if lower_path.staridx[0] == 1:  # Star region starts at beginning of path
                    if lower_path.staridx[1] == len(lower_path.orders)-2:  # Star region ends near end of path
                        # Choose search direction based on order parameter direction
                        if lower_path.orders[0][0] >= lower_path.orders[-1][0]:  # First op is larger than last op, extend towards first
                            idx1l = next(i for i in range(lower_path.staridx[0]-1, -1, -1)
                                        if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") + 1
                            idx1r = next(i for i in range(lower_path.staridx[0], len(lower_path.orders))
                                        if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
                        else:  # First op is smaller than last op, extend towards last
                            idx1l = next(i for i in range(lower_path.staridx[1], -1, -1) if 
                                        (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) + 1
                            idx1r = next(i for i in range(lower_path.staridx[1]+1, len(lower_path.orders)) 
                                        if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
                    else:  # Star region ends earlier in path
                        idx1l = next(i for i in range(lower_path.staridx[1], -1, -1) if 
                                (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) + 1
                        idx1r = next(i for i in range(lower_path.staridx[1]+1, len(lower_path.orders)) 
                                if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
                else:  # Star region starts later in path
                    idx1l = next(i for i in range(lower_path.staridx[0]-1, -1, -1) if 
                                (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) + 1
                    idx1r = next(i for i in range(lower_path.staridx[0], len(lower_path.orders)) 
                                if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
            
            # Handle paths by their starting direction (L = starting from left, R = starting from right)
            elif lower_path.meta[0][0] == "L":  # LMR or LML paths
                idx1l = next(i for i in range(lower_path.staridx[1], -1, -1) 
                    if (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) + 1
                idx1r = next(i for i in range(lower_path.staridx[1]+1, len(lower_path.orders))
                    if check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M") - 1
            else:  # RML path
                idx1l = next(i for i in range(lower_path.staridx[0]-1, -1, -1) if 
                        (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) + 1
                idx1r = next(i for i in range(lower_path.staridx[0], len(lower_path.orders)) 
                    if (check_position(lower_path.orders[i], ensembles[idx+1].intfs["L"], ensembles[idx+1].intfs["R"]) != "M")) - 1
        except:
            # Log exception details and reject the swap if star region can't be determined
            logger.exception("Error determining star region for lower path in upper ensemble")
            return "NCR", (upper_path, ptype2), (lower_path, ptype1)
            
        try:
            #-----------------------------------------------------------------
            # PART 2: Calculate valid star region indices for upper path
            # when moved to the lower ensemble (idx)
            #-----------------------------------------------------------------
            
            if upper_path.meta[0] == "LML":  # Special handling for left-middle-left paths
                if upper_path.staridx[0] == 1:  # Star region starts at beginning of path
                    if upper_path.staridx[1] == len(upper_path.orders)-2:  # Star region ends near end of path
                        # Choose search direction based on order parameter direction
                        if upper_path.orders[0][0] <= upper_path.orders[-1][0]:  # First op is smaller than last op, extend towards first 
                            idx2l = next(i for i in range(upper_path.staridx[0]-1, -1, -1)
                                if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") + 1
                            idx2r = next(i for i in range(upper_path.staridx[0], len(upper_path.orders)) 
                                if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
                        else:  # First op is larger than last op, extend towards last
                            idx2l = next(i for i in range(upper_path.staridx[1], -1, -1) if 
                                        (check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M")) + 1
                            idx2r = next(i for i in range(upper_path.staridx[1]+1, len(upper_path.orders)) 
                                        if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
                    else:  # Star region ends earlier in path
                        idx2l = next(i for i in range(upper_path.staridx[1], -1, -1) if 
                                    (check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M")) + 1
                        idx2r = next(i for i in range(upper_path.staridx[1]+1, len(upper_path.orders)) 
                                    if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
                else:  # Star region starts later in path
                    idx2l = next(i for i in range(upper_path.staridx[0]-1, -1, -1) if 
                                (check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M")) + 1
                    idx2r = next(i for i in range(upper_path.staridx[0], len(upper_path.orders)) 
                                if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
            
            # Handle paths by their starting direction
            elif upper_path.meta[0][0] == "L":  # LMR paths
                idx2l = next(i for i in range(upper_path.staridx[0]-1, -1, -1) 
                    if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") + 1
                idx2r = next(i for i in range(upper_path.staridx[0], len(upper_path.orders))
                    if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
            else:  # RMR or RML paths
                idx2l = next(i for i in range(upper_path.staridx[1], -1, -1) 
                    if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") + 1
                idx2r = next(i for i in range(upper_path.staridx[1]+1, len(upper_path.orders)) 
                    if check_position(upper_path.orders[i], ensembles[idx].intfs["L"], ensembles[idx].intfs["R"]) != "M") - 1
        except:
            # Log exception details and reject the swap if star region can't be determined
            logger.exception("Error determining star region for upper path in lower ensemble")
            return "NCR", (upper_path, ptype2), (lower_path, ptype1)
    else:
        # Reject swap if either path doesn't meet basic requirements for target ensemble
        return "NCR", (upper_path, ptype2), (lower_path, ptype1)
    
    #-----------------------------------------------------------------
    # PART 3: Finalize the swap if star regions are valid
    #-----------------------------------------------------------------
    
    # Ensure the star region indices are valid (start index <= end index)
    if idx1l <= idx1r and idx2l <= idx2r:
        # Update star region indices and path types for both paths
        lower_path.staridx = (idx1l, idx1r)
        lower_path.meta[0] = ptype1
        upper_path.staridx = (idx2l, idx2r)
        upper_path.meta[0] = ptype2
        # Accept the swap
        return "ACC", (upper_path, ptype2), (lower_path, ptype1)
    else:
        # Reject if determined star regions are invalid
        logger.error("Swap indices out of bounds: lower_path[%d:%d], upper_path[%d:%d]", 
                     idx1l, idx1r, idx2l, idx2r)
        return "NCR", (upper_path, ptype2), (lower_path, ptype1)
    
def kick_star(ens):
    """ Generates a new initial path for an [i*] ensemble by creating a shootpoint 
    near an interface and propagating in both directions.
    
    This function is used to create a valid path in an [i*] ensemble when no previous
    paths exist. It keeps trying to generate a path until successful by:
    1. Placing a point near an appropriate interface based on ensemble type
    2. Assigning random velocities
    3. Propagating in both directions and extending as needed
    4. Validating the path meets all ensemble requirements
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        The ensemble for which to generate an initial path
        
    Returns
    -------
    None
        The function adds the generated path directly to the ensemble's paths list
        
    Notes
    -----
    This is essentially a special case of a shooting move without a previous path.
    It uses a persistent trial approach that guarantees a successful path generation.
    """
    while True:
        if ens.settings["dim"] == 1:
            if ens.id == 0:
                sh = (ens.intfs["R"]*(1 - np.sign(ens.intfs["R"])*0.02)-0.0001, ens.engine.draw_velocities())
            elif ens.id == 1:
                sh = (ens.intfs["L"]*(1 + np.sign(ens.intfs["L"])*0.02)+0.0001, ens.engine.draw_velocities())
            else:
                sh = (ens.intfs["M"]*(1 - np.sign(ens.intfs["M"])*0.02)-0.0001, ens.engine.draw_velocities())
        elif ens.settings["dim"] == 2:
            orth_min = 0.
            orth_max = 0.3
            # orth_min = -2
            # orth_max = 2
            if ens.id == 0:
                sh = (np.asarray([(orth_max-orth_min)*np.random.rand()+orth_min, ens.intfs["R"]*(1 - np.sign(ens.intfs["R"])*0.02)-0.0001]), ens.engine.draw_velocities())
            elif ens.id == 1:
                sh = (np.asarray([(orth_max-orth_min)*np.random.rand()+orth_min, ens.intfs["L"]*(1 + np.sign(ens.intfs["L"])*0.02)+0.0001]), ens.engine.draw_velocities())
            else:
                sh = (np.asarray([(orth_max-orth_min)*np.random.rand()+orth_min, ens.intfs["M"]*(1 - np.sign(ens.intfs["M"])*0.02)-0.0001]), ens.engine.draw_velocities())
        shootpoint_op = ens.orderparameter.calculate(sh)
        logger.debug("Init from ph {} with op {}".format(
                sh, shootpoint_op))
        bw_status, bw_tuple = propagate(ens, sh, -1., ens.max_len-2)
        # if unsuccessful, return the status and the partially propagated path
        if bw_status != "ACC": 
            continue
        # if successful, we continue propagating forwards
        fw_status, fw_tuple = propagate(ens, sh, 1.,
                                        ens.max_len-len(bw_tuple[0])-1)
        # if unsuccessful, return the status and the partially propagated path
        if fw_status != "ACC":
            continue
        # If succesful, the new path should satisfy the crossing conditions.
        # logger.debug("Time origin of new path: {}".format(len(bw_tuple[0])-sh_id))
        ptype = ens.get_ptype(Path(bw_tuple[0] + [sh] + fw_tuple[0],
                        bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                        ens.id))
        new_path = Path(bw_tuple[0] + [sh] + fw_tuple[0],
                        bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                        ens.id, [ptype, 0, shootpoint_op])
        # if the ensemble is a primed PPTIS ensemble, we have to check whether an 
        # illegal pathtype has occurred. If so, we reject the move with flag 'ILL'. 
        if ptype in ens.illegal_pathtypes:
            continue
        # We have to check whether the new path satisfies the crossing conditions.
        # TODO: all the above can be done in 'check_path' method of Ensemble, which 
        # should be rebuilt for this purpose. 
        if not ens.check_cross(new_path):
            continue
        if ptype == "RMR" or ptype == "LML":
            prop_idx = np.random.choice([0, -1])
            rev = -np.sign(prop_idx+0.5)
            prop_point = new_path.phasepoints[prop_idx]
            # np.random.seed(0)
            ext_status, ext_tuple = ext_propagate(ens, prop_point, 
                                                rev, ens.max_len-len(new_path.orders))
            # np.random.seed(0)
            # ext_status2, ext_tuple2 = propagate_old(ens, prop_point, 
            #                                     rev, ens.max_len-num_shootpoints(new_path.orders, ens.intfs["L"], ens.intfs["R"]), True)
            # assert ext_status == ext_status2
            # assert ext_tuple == ext_tuple2
            if rev == -1:
                ext_path = Path(ext_tuple[0] + new_path.phasepoints,
                                ext_tuple[1] + new_path.orders,
                                ens.id, [ptype, 1 if ptype=="LML" else -1, shootpoint_op])
                li = len(ext_tuple[1])+1; ri = len(ext_path.orders)-2
            else:
                ext_path = Path(new_path.phasepoints + ext_tuple[0],
                                new_path.orders + ext_tuple[1],
                                ens.id, [ptype, -1 if ptype=="LML" else 1, shootpoint_op])
                li = 1; ri = len(new_path.orders)-2
            if ext_status != "ACC":
                continue
            else:
                ext_path.staridx = (int(li), int(ri))
                ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
                break
        else:
            # np.random.seed(0)
            bext_status, bext_tuple = ext_propagate(ens, new_path.phasepoints[0], -1., ens.max_len-len(new_path.orders))
            # np.random.seed(0)
            # bext_status2, bext_tuple2 = propagate_old(ens, new_path.phasepoints[0], -1., ens.max_len-len(new_path.orders), True)
            # assert bext_status == bext_status2
            # assert bext_tuple == bext_tuple2
            if bext_status != "ACC": 
                continue
            # np.random.seed(0)
            fext_status, fext_tuple = ext_propagate(ens, new_path.phasepoints[-1], 1.,
                                    ens.max_len-len(bext_tuple[0])-len(new_path.orders))
            # np.random.seed(0)
            # fext_status2, fext_tuple2 = propagate_old(ens, new_path.phasepoints[-1], 1.,
            #                         ens.max_len-len(bext_tuple[0])-len(new_path.orders), True)
            # assert fext_status == fext_status2
            # assert fext_tuple == fext_tuple2
            if fext_status != "ACC":
                continue
            else:
                logger.debug("Extension performed successfully.")
                ext_path = Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                    bext_tuple[1] + new_path.orders + fext_tuple[1],
                                    ens.id, [ptype, 0, "ACC", shootpoint_op])
                # if ens.ens_type == "i*_0star" and ext_path.orders[0][0] <= ens.intfs["L"] and ext_path.orders[-1][0] <= ens.intfs["L"]:
                #     ptype = "LML"
                #     ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
                ext_path.staridx = (len(bext_tuple[1])+1, len(bext_tuple[1]) + len(new_path.orders)-2)
                break
    ens.paths.append(ext_path)
    ens.last_path = ext_path
    ens.update_data("ACC", (ext_path, ptype), "ld", 0)

    return


def ext_propagate(ens, ext_pt, reverse, maxlen):
    """Extends an [i*] path from a phasepoint in ensemble ens, until 
    a turn is detected, a stable state is reached, or the maximum length is reached.
    
    This specialized propagation function is used within the [i*] ensemble framework
    to extend paths beyond the transition region until appropriate termination conditions
    are met. Unlike regular propagation which stops at interfaces, this continuation
    tracks when paths "turn around" or reach stable states.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble to propagate in
    ext_pt : phasepoint 
        Phasepoint to propagate from (tuple (x,v))
    reverse : float 
        Whether to propagate forwards (1.) or backwards (-1.)
    maxlen : int
        Maximum length of the path to generate

    Returns
    -------
    status : str
        Status of the propagation ("ACC" for successful extension, otherwise error code)
    trial_tuple : tuple
        Tuple containing (phasepoints, order_parameters, ensemble_id) of the extended path

    Notes
    -----
    The returned path does **not** include the starting point (ext_pt)!
    This function handles the special termination conditions needed for [i*] ensembles:
    - Path reaching stable state A or B
    - Path making a "turn" (going back toward the interface it started from)
    """
    if reverse == -1:
        logger.debug("Propagating backwards")
        conds = {"cond": ens.start_conditions,
                 "rej_maxlen": "BTX",
                 "type_cond": "start"}
    elif reverse == 1:
        logger.debug("Propagating forwards")
        conds = {"cond": ens.end_conditions,
                 "rej_maxlen": "FTX",
                 "type_cond": "end"}
    else:
        raise ValueError("reverse must be either 1 or -1")

    # Calculate order parameter for the starting point
    ext_op = ens.orderparameter.calculate(ext_pt)
    phs, ops = [], []  # Lists to store phasepoints and order parameters
    run_len = 0
    run_worthy = True
    
    # Create starting point with velocity in the appropriate direction
    ph = (ext_pt[0], reverse*ext_pt[1])
    
    # Determine initial position relative to interfaces
    pos_star = check_position(ext_op, ens.intfs['L'], ens.intfs['R'])
    AB_pos = check_position(ext_op, ens.intfs['all'][0], ens.intfs['all'][-1])
    
    # Check if already in stable state A or B
    if AB_pos != "M":
        run_worthy = False
        msg = f"Path crossed into {'A' if AB_pos == 'L' else 'B'}, which terminates this [i*] path."
        logger.debug(msg)
        status = 'ACC'
        
    # Main propagation loop
    while run_worthy:
        # Take a step with the engine
        ph = ens.engine.step(ph)
        
        # Calculate order parameter for new position
        op = ens.orderparameter.calculate(ph)
        
        # Store phasepoint and order parameter with correct velocity direction
        phs.append((ph[0], reverse*ph[1]))
        ops.append(op)
        run_len += 1
        
        # Check if maximum path length reached
        if run_len >= maxlen:
            logger.debug(f"!! Path reached max_len ({run_len} >= {maxlen}). !!")
            print(f"!! Path in ensemble {ens.id} reached max_len ({run_len} >= {maxlen}). !!")
            status = conds['rej_maxlen']
            run_worthy = False
        else:
            # Check if path reached stable state A or B
            AB_pos = check_position(op, ens.intfs['all'][0], ens.intfs['all'][-1])
            if AB_pos != "M":
                run_worthy = False
                msg = f"Path crossed into {'A' if AB_pos == 'L' else 'B'}, which terminates this [i*] path."
                logger.debug(msg)
                status = 'ACC'
            # Check if path made a turn
            elif turn_detected(ens, pos_star, [ens.orderparameter.calculate(ext_pt)] + ops):
                run_worthy = False
                msg = f"Path made a turn while moving {'forwards' if reverse == 1 else 'backwards'}."
                logger.debug(msg)
                status = 'ACC'
    
    # Prepare return value based on propagation direction
    if reverse == -1:
        # For backward propagation, reverse the order of points
        trial_tuple = (phs[::-1], ops[::-1], ens.id)
    else:
        trial_tuple = (phs, ops, ens.id)

    return status, trial_tuple

def turn_detected(ens, pos, ops):
    """Detects if a path has made a turn in order parameter space.
    
    This function checks whether a path that was moving in one direction in order parameter
    space has turned back. This is an important termination condition for [i*] paths, as
    it indicates the path is returning to the region it came from rather than proceeding
    to the other stable state.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        The ensemble containing interface definitions
    pos : str
        Starting position relative to interfaces ("L" for left, "R" for right, "M" for middle)
    ops : list
        List of order parameters along the path
        
    Returns
    -------
    bool
        True if a turn is detected, False otherwise
        
    Notes
    -----
    The algorithm identifies the extreme value reached in the order parameter,
    then checks if the path returned past a specific interface after reaching that extreme.
    """
    intfs = ens.intfs['all']
    # Determine direction based on starting position
    lr = -1 if pos == "L" else (1 if pos == "R" else None)
    
    # Find extreme value in the appropriate direction
    extr_op = max(ops) if lr==1 else min(ops)
    
    # Find eligible interfaces for detecting turns
    elig_intfs = [int for int in intfs if lr*int <= lr*extr_op[0]]
    # extr_idx = intfs.index(elig_intfs[np.abs(elig_intfs - extr_op).argmin()])
    # cond_intf = elig_intfs[np.abs(elig_intfs - extr_op).argmin()-lr]
    cond_intf = elig_intfs[1 if lr==-1 else -2]
    
    # If we're still at the extreme point, no turn detected
    if ops[-1] == extr_op or extr_op is None:
        return False

    # extr_intf = intfs[extr_idx]
    ops_elig = np.array([op[0] for op in ops[ops.index(extr_op):]])
    
    # Check if any of these points cross back over the condition interface
    return np.any(lr*ops_elig < lr*cond_intf)

def num_shootpoints(orders, l, r):
    """Counts the number of phasepoints in the shooting region.
    
    Parameters
    ----------
    orders : list
        List of order parameters for all phasepoints
    l : float
        Left interface of shooting region
    r : float
        Right interface of shooting region
        
    Returns
    -------
    int
        Number of phasepoints with order parameters between l and r
    """
    ops = np.array(orders)
    return np.count_nonzero(np.logical_and(ops >= l, ops <= r))

def pg_check_path(ens, path):
    """ Checks whether a path is valid for a given [i*] ensemble.

    This function verifies that a path meets all the criteria required for the
    specified ensemble. It identifies the path type (LML, RMR, LMR, RML) and 
    checks if this type is allowed in the ensemble.

    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble to check the path against
    path : :py:class:`Path` object
        Path to validate

    Returns
    -------
    valid : bool
        True if the path is valid for the ensemble, False otherwise
    ptype : str
        The identified path type ("LML", "RMR", "LMR", "RML", or "***" for invalid)
        
    Notes
    -----
    The function analyzes the path's order parameter extremes and crossings to
    determine its type and validity according to the ensemble's requirements.
    """
    ordermin = (min([op[0] for op in path.orders]), np.argmin([op[0] for op in path.orders]))
    ordermax = (max([op[0] for op in path.orders]), np.argmax([op[0] for op in path.orders]))
    if (ens.id == 1 and ordermin[0] > ens.intfs["all"][0])\
        \
        or (np.all(np.asarray(path.orders) < [ens.intfs["L"]]) or np.all(np.asarray(path.orders) > [ens.intfs["R"]])\
            or not np.any(np.logical_and([ens.intfs["L"]] < np.asarray(path.orders), np.asarray(path.orders) < [ens.intfs["R"]]))\
            or check_position([ordermax[0]], ens.intfs["L"], ens.intfs["L"] if ens.id == 1 else ens.intfs["M"]) == "M"\
            or check_position([ordermin[0]], ens.intfs["L"] if ens.id == 1 else ens.intfs["M"], ens.intfs["R"]) == "M")\
            or (ens.id == 1 and not (not path.orders[1][0] >= ens.intfs["R"] or not path.orders[-2][0] >= ens.intfs["R"]))\
            or (ens.id == len(ens.intfs["all"])-1 and not (not path.orders[1][0] <= ens.intfs["L"] or not path.orders[-2][0] <= ens.intfs["L"])):# check if valid "staple" path
        return False, "***" # not a valid path
    
    elif (ens.id == 1 and path.orders[-1][0] < ens.intfs["L"] and path.orders[0][0] < ens.intfs["L"]\
          and ordermax[0] < ens.intfs["R"]) or (ens.id == 2 and path.orders[-1][0] < ens.intfs["L"] and path.orders[0][0] < ens.intfs["L"] and ordermax[0] >= ens.intfs["M"]): # max already checked before
        return True, "LML"

    # Use the new function to validate turns
    valid_turns, start_extr, end_extr = validate_staple(ens, path)
    
    if not valid_turns:
        return False, "***"
     
    if check_position([start_extr] if start_extr < end_extr else [end_extr], ens.intfs["L"], ens.intfs["M"])== "M" if ens.id > 2 else \
        check_position([ordermin[0]], ens.intfs["L"], ens.intfs["R"])  == "M":
        ptype = "RMR"
    elif check_position([end_extr] if start_extr < end_extr else [start_extr], ens.intfs["M"], ens.intfs["R"]) == "M" if ens.id > 2 else \
        check_position([ordermax[0]], ens.intfs["L"], ens.intfs["R"]) == "M":
        ptype = "LML"
    else:
        LtR = start_extr < end_extr
        ptype = "LMR" if LtR else "RML" 

    # Conditions
    valid = (len(ens.start_conditions) == 0 or ptype[0] in ens.start_conditions) and \
            (len(ens.end_conditions) == 0 or ptype[2] in ens.end_conditions) and \
            (len(ens.cross_conditions) == 0 or ptype[1] in ens.cross_conditions) and \
            ptype not in ens.illegal_pathtypes
    return valid, ptype

def shooting_move_old(ens, level=0):
    """ Performs a shooting move in the ensemble.

    [DEPRECATED - Retained for reference purposes]
    This is the original shooting move implementation kept for comparison.
    Please use pg_shooting_move() for new code.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble in which the shooting move is performed
    level : int
        The level of the path to shoot from in ensemble ens. Default is 0.

    Returns
    -------
    success : string
        String indicating whether the shooting move was successful
    new_path : :py:class:`Path` object
        New path generated by the shooting move

    """
    path = ens.paths[level]  # last accepted path
    pathlen = len(path.phasepoints)
    if ens.ens_type in ["body_i*", "i*_0star"]:
        poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["L"] and path.orders[i][0] <= ens.intfs["R"] and i >= path.staridx[0] and i <= path.staridx[1])]
        if ens.ens_type == "i*_0star":
            poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["all"][0] and path.orders[i][0] <= ens.intfs["all"][1] and i >= path.staridx[0] and i <= path.staridx[1])]
        else:
            poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["L"] and path.orders[i][0] <= ens.intfs["R"] and i >= path.staridx[0] and i <= path.staridx[1])]
        n_ph = len(poss_sh)
        sh_id = np.random.choice(poss_sh)
    else:
        n_ph = pathlen
        sh_id = np.random.randint(1,n_ph-1)
    shootpoint = (path.phasepoints[sh_id][0],
                  ens.engine.draw_velocities())
    shoot_maxlen = min(n_ph/np.random.random(), ens.max_len)
    # We will not recalculate the orderparameter for this phasepoint, as 
    # external engines may save phasepoints at a lower precision. This can 
    # lead to the recalculated phasepoint shifting position w.r.t. an interface,
    # resulting in all sorts of nasty problems.
    # shootpoint_op = ens.orderparameter.calculate(shootpoint)
    shootpoint_op = path.orders[sh_id]
    logger.debug("Shooting from ph {} (idx: {}) with op {}".format(
        shootpoint, sh_id, shootpoint_op))
    # We now start propagating the shootpoint backwards first, because often
    # the backwards part (corresponding to the starting condition) is more
    # restrictive than the forwards part (corresponding to the end condition).
    # propagate backwards. Maxlen = shoot_maxlen-1, because shootpoint is 1
    bw_status, bw_tuple = propagate_old(ens, shootpoint, -1., shoot_maxlen-1)
    # if unsuccessful, return the status and the partially propagated path
    if bw_status != "ACC": 
        logger.debug("Backwards propagation not successful: {}".format(
            bw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0]+[shootpoint], bw_tuple[1]+[shootpoint_op], ens.id))
        return bw_status, Path(bw_tuple[0]+[shootpoint],
                               bw_tuple[1]+[shootpoint_op],
                               ens.id, [ptype, 0, bw_status, shootpoint_op])
    # if successful, we continue propagating forwards
    fw_status, fw_tuple = propagate_old(ens, shootpoint, 1.,
                                    shoot_maxlen-len(bw_tuple[0]))
    # if unsuccessful, return the status and the partially propagated path
    if fw_status != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(
            fw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id))
        return fw_status, Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id, [ptype, 0, fw_status, shootpoint_op])
    # If succesful, the new path should satisfy the crossing conditions.
    # logger.debug("Time origin of new path: {}".format(len(bw_tuple[0])-sh_id))
    ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id))
    new_path = Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id, [ptype, 0, shootpoint_op])
    # if the ensemble is a primed PPTIS ensemble, we have to check whether an 
    # illegal pathtype has occurred. If so, we reject the move with flag 'ILL'. 
    
    ptype = ens.get_ptype(new_path)
    if ptype in ens.illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype))
        new_path.meta = [ptype, 0, "ILL", shootpoint_op]
        return "ILL", new_path
    # We have to check whether the new path satisfies the crossing conditions.
    # TODO: all the above can be done in 'check_path' method of Ensemble, which 
    # should be rebuilt for this purpose. 
    if not ens.check_cross(new_path):
        logger.debug("New path does not satisfy ensemble crossing conditions")
        new_path.meta = [ptype, 0, "NCR", shootpoint_op]
        return "NCR", new_path
    
    elif ens.ens_type in ["body_i*", "i*_0star"]:
        ptype = ens.get_ptype(new_path)
        if ptype == "RMR" or ptype == "LML":
            prop_idx = np.random.choice([0, -1])
            rev = -np.sign(prop_idx+0.5)
            prop_point = new_path.phasepoints[prop_idx]
            np.random.seed(0)
            ext_status, ext_tuple = propagate_old(ens, prop_point, 
                                              rev, shoot_maxlen-num_shootpoints(new_path.orders, ens.intfs["L"], ens.intfs["R"]), True)
            if rev == -1:
                ext_path = Path(ext_tuple[0] + new_path.phasepoints,
                                ext_tuple[1] + new_path.orders,
                                ens.id, [ptype, 1 if ptype=="LML" else -1, shootpoint_op])
                li = len(ext_tuple[1])+1; ri = len(ext_path.orders)-2
            else:
                ext_path = Path(new_path.phasepoints + ext_tuple[0],
                                new_path.orders + ext_tuple[1],
                                ens.id, [ptype, -1 if ptype=="LML" else 1, shootpoint_op])
                li = 1; ri = len(new_path.orders)-2
            if ext_status != "ACC":
                logger.debug("Half extension not successful: {}".format(
                    ext_status))
                ext_path.meta = [ptype, 0, ext_status, shootpoint_op]
                return ext_status, (ext_path, ptype)
            else:
                ext_path.staridx = (int(li), int(ri))
                logger.debug("Extension performed successfully.")
                ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
                return "ACC", (ext_path, ptype)
        else:
            np.random.seed(0)
            bext_status, bext_tuple = propagate_old(ens, new_path.phasepoints[0], -1., shoot_maxlen-num_shootpoints(new_path.orders, ens.intfs["L"], ens.intfs["R"]), True)
            if bext_status != "ACC": 
                logger.debug("Backwards extension not successful: {}".format(
                    bext_status))
                return bext_status, (Path(bext_tuple[0]+new_path.phasepoints,
                                    bext_tuple[1]+new_path.orders,
                                    ens.id, [ptype, 0, bext_status, shootpoint_op]), ptype)
            
            np.random.seed(0)
            fext_status, fext_tuple = propagate_old(ens, new_path.phasepoints[-1], 1.,
                                    shoot_maxlen-len(bext_tuple[0])-num_shootpoints(new_path.orders, ens.intfs["L"], ens.intfs["R"]), True)
            if fext_status != "ACC":
                logger.debug("Forwards extension not successful: {}".format(
                    fext_status))
                return fext_status, (Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                    bext_tuple[1] + new_path.orders + fext_tuple[1],
                                    ens.id, [ptype, 0, fext_status, shootpoint_op]), ptype)
            else:
                logger.debug("Extension performed successfully.")
                ext_path = Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                    bext_tuple[1] + new_path.orders + fext_tuple[1],
                                    ens.id, [ptype, 0, "ACC", shootpoint_op])
                if ens.ens_type == "i*_0star" and ext_path.orders[0][0] <= ens.intfs["L"] and ext_path.orders[-1][0] <= ens.intfs["L"]:
                    ptype = "LML"
                    ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
                ext_path.staridx = (len(bext_tuple[1])-1, len(bext_tuple[1]) + len(new_path.orders)-2)
                return "ACC", (ext_path, ptype)
    else:
        logger.debug("New path satisfies ensemble crossing conditions.")
        new_path.meta = [ptype, 0, "ACC", shootpoint_op]
        return "ACC", new_path
    
def propagate_old(ens, sh, reverse, maxlen, ext=False):
    """Propagate from a phasepoint sh in ensemble ens, until either one of 
    the extremal conditions (ext_cond) is met, or the maximum length of the 
    path (maxlen) is reached.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble to propagate in
    sh : phasepoint 
        Phasepoint to propagate from (tuple (x,v))
    reverse : float 
        Whether to propagate forwards (1.) or backwards (-1.)
    maxlen : int
        Maximum length of the path to generate

    Returns
    -------
    status : str
        Status of the propagation.
    trial_tuple : tuple
        tuple of (phs, ops, ens.id) of the trial path

    Notes
    -----
    The returned path does **not** include the shooting point!

    """
    if reverse == -1:
        logger.debug("Propagating backwards")
        conds = {"cond": ens.start_conditions,
                 "rej_intf": "BWI",
                 "rej_maxlen": "BTL",
                 "type_cond": "start"}
    elif reverse == 1:
        logger.debug("Propagating forwards")
        conds = {"cond": ens.end_conditions,
                 "rej_intf": "FWI",
                 "rej_maxlen": "FTL",
                 "type_cond": "end"}
    else:
        raise ValueError("reverse must be either 1 or -1")

    phs, ops = [], []
    run_len = 0
    run_worthy = True
    ph = (sh[0], reverse*sh[1])
    pos_star = None
    while run_worthy:
        #logger.debug("ph = %s", ph)
        ph = ens.engine.step(ph)
        op = ens.orderparameter.calculate(ph)
        phs.append((ph[0], reverse*ph[1]))
        ops.append(op)
        LR_pos = check_position(op, ens.intfs['L'], ens.intfs['R'])
        run_len += 1
        if LR_pos in ens.extremal_conditions:
            if ext:
                run_len -= 1
                pos_star = check_position(sh, ens.intfs['L'], ens.intfs['R'])
                AB_pos = check_position(op, ens.intfs['all'][0], ens.intfs['all'][-1])
                if AB_pos != "M":
                    run_worthy = False
                    msg = f"Path crossed into {'A' if AB_pos == 'L' else 'B'}, which terminates this [i*] path."
                    logger.debug(msg)
                    status = 'ACC'
            else:
                run_worthy = False
                if LR_pos in conds['cond']:
                    msg = f"Path crossed {LR_pos}, which is part of the "
                    msg += f"{conds['type_cond']} conditions {conds['cond']}."
                    logger.debug(msg)
                    status = "ACC"
                else:
                    msg = f"Path crossed {LR_pos}, which is not part of the "
                    msg += f"{conds['type_cond']} conditions {conds['cond']}."
                    logger.debug(msg)
                    status = conds['rej_intf']
        elif run_len >= maxlen:
            logger.debug(f"Path too long ({run_len} >= {maxlen}).")
            status = conds['rej_maxlen']
            run_worthy = False
            
        if pos_star is not None:
            if AB_pos != "M":
                run_worthy = False
                msg = f"Path crossed into {'A' if AB_pos == 'L' else 'B'}, which terminates this [i*] path."
                logger.debug(msg)
                status = 'ACC'
            elif turn_detected(ens, pos_star, ops):
                run_worthy = False
                msg = f"Path made a turn while moving {'forwards' if reverse == 1 else 'backwards'}."
                logger.debug(msg)
                status = 'ACC'
    
    if reverse == -1:
        trial_tuple = (phs[::-1], ops[::-1], ens.id)
    else:
        trial_tuple = (phs, ops, ens.id)

    return status, trial_tuple