import numpy as np
import logging

from funcs import check_position
from path import Path
from moves import propagate

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

def pg_shooting_move(ens, level=0):
    """ Performs a shooting move in an [i*] ensemble.

    A random phasepoint in the REPPTIS region between interface i-1 and i+1 of 
    the last_accepted path in the ensemble is chosen,
    excluding the first and last phasepoints. This new phasepoint, called the
    shootpoint, is given new velocities drawn from the Maxwell-Boltzmann
    distribution. A new path is generated by propagating the shootpoint
    backwards and forwards in time. Note that backwards propagation is done
    by reversing the velocities of the shootpoint.

    To obey detailed balance, the new path is accepted with probability
    min(1, len(old_path)/len(new_path)). For efficiency sake, we draw a random
    number between 0 and 1 and propagate the new_path until len(old_path)/Q.

    The new_path is checked whether it is an acceptable path for the ensemble.

    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble in which the shooting move is performed
    level : int
        The level of the path to shoot from in ensemble ens. Default is 0.

    Returns
    -------
    success : string
        String indicating whether the shooting move was successful
    new_path : :py:class:`Path` object
        New path generated by the shooting move

    """
    path = ens.paths[level]  # last accepted path
    pathlen = len(path.phasepoints)

    if ens.ens_type == "i*_0star":
        poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["all"][0] and path.orders[i][0] <= ens.intfs["all"][1] and i >= path.staridx[0] and i <= path.staridx[1])]
    else:
        poss_sh = [i for i in range(pathlen) if (path.orders[i][0] >= ens.intfs["L"] and path.orders[i][0] <= ens.intfs["R"] and i >= path.staridx[0] and i <= path.staridx[1])]
    n_ph = len(poss_sh)
    sh_id = np.random.choice(poss_sh)

    shootpoint = (path.phasepoints[sh_id][0],
                  ens.engine.draw_velocities())
    shoot_maxlen = min(n_ph/np.random.random(), ens.max_len)
    # We will not recalculate the orderparameter for this phasepoint, as 
    # external engines may save phasepoints at a lower precision. This can 
    # lead to the recalculated phasepoint shifting position w.r.t. an interface,
    # resulting in all sorts of nasty problems.
    # shootpoint_op = ens.orderparameter.calculate(shootpoint)
    shootpoint_op = path.orders[sh_id]
    logger.debug("Shooting from ph {} (idx: {}) with op {}".format(
        shootpoint, sh_id, shootpoint_op))
    # We now start propagating the shootpoint backwards first, because often
    # the backwards part (corresponding to the starting condition) is more
    # restrictive than the forwards part (corresponding to the end condition).
    # propagate backwards. Maxlen = shoot_maxlen-1, because shootpoint is 1
    bw_status, bw_tuple = propagate(ens, shootpoint, -1., shoot_maxlen-1)
    # if unsuccessful, return the status and the partially propagated path
    if bw_status != "ACC": 
        logger.debug("Backwards propagation not successful: {}".format(
            bw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0]+[shootpoint], bw_tuple[1]+[shootpoint_op], ens.id))
        return bw_status, Path(bw_tuple[0]+[shootpoint],
                               bw_tuple[1]+[shootpoint_op],
                               ens.id, [ptype, 0, bw_status, shootpoint_op])
    # if successful, we continue propagating forwards
    fw_status, fw_tuple = propagate(ens, shootpoint, 1.,
                                    shoot_maxlen-len(bw_tuple[0]))
    # if unsuccessful, return the status and the partially propagated path
    if fw_status != "ACC":
        logger.debug("Forwards propagation not successful: {}".format(
            fw_status))
        ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id))
        return fw_status, Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                               bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                               ens.id, [ptype, 0, fw_status, shootpoint_op])
    # If succesful, the new path should satisfy the crossing conditions.
    # logger.debug("Time origin of new path: {}".format(len(bw_tuple[0])-sh_id))
    ptype = ens.get_ptype(Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id))
    new_path = Path(bw_tuple[0] + [shootpoint] + fw_tuple[0],
                    bw_tuple[1] + [shootpoint_op] + fw_tuple[1],
                    ens.id, [ptype, 0, shootpoint_op])
    # if the ensemble is a primed PPTIS ensemble, we have to check whether an 
    # illegal pathtype has occurred. If so, we reject the move with flag 'ILL'. 
    
    ptype = ens.get_ptype(new_path)

    if ptype in ens.illegal_pathtypes:
        logger.info("Illegal pathtype {} for primed ensemble".format(ptype))
        new_path.meta = [ptype, 0, "ILL", shootpoint_op]
        return "ILL", new_path
    # We have to check whether the new path satisfies the crossing conditions.
    # TODO: all the above can be done in 'check_path' method of Ensemble, which 
    # should be rebuilt for this purpose. 
    if not ens.check_cross(new_path):
        logger.debug("New path does not satisfy ensemble crossing conditions")
        new_path.meta = [ptype, 0, "NCR", shootpoint_op]
        return "NCR", new_path
    
    if ptype == "RMR" or ptype == "LML":
        prop_idx = np.random.choice([0, -1])
        rev = -np.sign(prop_idx+0.5)
        prop_point = new_path.phasepoints[prop_idx]
        ext_status, ext_tuple = ext_propagate(ens, prop_point, 
                                            rev, ens.max_len-num_shootpoints(new_path.orders, ens.intfs["L"], ens.intfs["R"]))
        if rev == -1:
            ext_path = Path(ext_tuple[0] + new_path.phasepoints,
                            ext_tuple[1] + new_path.orders,
                            ens.id, [ptype, 1 if ptype=="LML" else -1, shootpoint_op])
            li = len(ext_tuple[1])+1; ri = len(ext_path.orders)-2
        else:
            ext_path = Path(new_path.phasepoints + ext_tuple[0],
                            new_path.orders + ext_tuple[1],
                            ens.id, [ptype, -1 if ptype=="LML" else 1, shootpoint_op])
            li = 1; ri = len(new_path.orders)-2
        if ext_status != "ACC":
            logger.debug("Half extension not successful: {}".format(
                ext_status))
            ext_path.meta = [ptype, 0, ext_status, shootpoint_op]
            return ext_status, (ext_path, ptype)
        else:
            ext_path.staridx = (int(li), int(ri))
            logger.debug("Extension performed successfully.")
            ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
            return "ACC", (ext_path, ptype)
    else:
        bext_status, bext_tuple = ext_propagate(ens, new_path.phasepoints[0], -1., ens.max_len-len(new_path.orders))
        if bext_status != "ACC": 
            logger.debug("Backwards extension not successful: {}".format(
                bext_status))
            return bext_status, (Path(bext_tuple[0]+new_path.phasepoints,
                                bext_tuple[1]+new_path.orders,
                                ens.id, [ptype, 0, bext_status, shootpoint_op]), ptype)
        
        fext_status, fext_tuple = ext_propagate(ens, new_path.phasepoints[-1], 1.,
                                ens.max_len-len(bext_tuple[0])-len(new_path.orders))
        if fext_status != "ACC":
            logger.debug("Forwards extension not successful: {}".format(
                fext_status))
            return fext_status, (Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                bext_tuple[1] + new_path.orders + fext_tuple[1],
                                ens.id, [ptype, 0, fext_status, shootpoint_op]), ptype)
        else:
            logger.debug("Extension performed successfully.")
            ext_path = Path(bext_tuple[0] + new_path.phasepoints + fext_tuple[0],
                                bext_tuple[1] + new_path.orders + fext_tuple[1],
                                ens.id, [ptype, 0, "ACC", shootpoint_op])
            if ens.ens_type == "i*_0star" and ext_path.orders[0][0] <= ens.intfs["L"] and ext_path.orders[-1][0] <= ens.intfs["L"]:
                ptype = "LML"
                ext_path.meta = [ptype, 0, "ACC", shootpoint_op]
            ext_path.staridx = (len(bext_tuple[1])-1, len(bext_tuple[1]) + len(new_path.orders)-2)
            return "ACC", (ext_path, ptype)
    

def ext_propagate(ens, ext_pt, reverse, maxlen):
    """Extend an [i*] path from a phasepoint sh in ensemble ens, until 
    a turn is detected, or the maximum length of the path (maxlen) is reached.
    
    Parameters
    ----------
    ens : :py:class:`Ensemble` object
        Ensemble to propagate in
    ext_pt : phasepoint 
        Phasepoint to propagate from (tuple (x,v))
    reverse : float 
        Whether to propagate forwards (1.) or backwards (-1.)
    maxlen : int
        Maximum length of the path to generate

    Returns
    -------
    status : str
        Status of the propagation.
    trial_tuple : tuple
        tuple of (phs, ops, ens.id) of the trial path

    Notes
    -----
    The returned path does **not** include the shooting point!

    """
    if reverse == -1:
        logger.debug("Propagating backwards")
        conds = {"cond": ens.start_conditions,
                 "rej_maxlen": "BTL",
                 "type_cond": "start"}
    elif reverse == 1:
        logger.debug("Propagating forwards")
        conds = {"cond": ens.end_conditions,
                 "rej_maxlen": "FTL",
                 "type_cond": "end"}
    else:
        raise ValueError("reverse must be either 1 or -1")

    phs, ops = [], []
    run_len = 0
    run_worthy = True
    ph = (ext_pt[0], reverse*ext_pt[1])
    pos_star = None
    while run_worthy:
        #logger.debug("ph = %s", ph)
        ph = ens.engine.step(ph)
        op = ens.orderparameter.calculate(ph)
        phs.append((ph[0], reverse*ph[1]))
        ops.append(op)
        run_len += 1
        if run_len >= maxlen:
            logger.debug(f"Path too long ({run_len} >= {maxlen}).")
            status = conds['rej_maxlen']
            run_worthy = False
        else:
            pos_star = check_position(ext_pt, ens.intfs['L'], ens.intfs['R'])
            AB_pos = check_position(op, ens.intfs['all'][0], ens.intfs['all'][-1])
            if AB_pos != "M":
                run_worthy = False
                msg = f"Path crossed into {'A' if AB_pos == 'L' else 'B'}, which terminates this [i*] path."
                logger.debug(msg)
                status = 'ACC'
            elif turn_detected(ens, pos_star, ops):
                run_worthy = False
                msg = f"Path made a turn while moving {'forwards' if reverse == 1 else 'backwards'}."
                logger.debug(msg)
                status = 'ACC'
    
    if reverse == -1:
        trial_tuple = (phs[::-1], ops[::-1], ens.id)
    else:
        trial_tuple = (phs, ops, ens.id)

    return status, trial_tuple


def turn_detected(ens, pos, ops):
    """Detects if a path has made a turn. This is a termination condition of a path in the [i*] ensemble.
    
    NOTE: also return extreme interface?
    """
    # ops_ = np.asarray(ops)
    intfs = ens.intfs['all']
    lr = -1 if pos == "L" else (1 if pos == "R" else None)
    # extr_op = lr*max(lr*ops_)
    extr_op = max(ops)[0] if lr==1 else min(ops)[0]
    elig_intfs = [int for int in intfs if lr*int <= lr*extr_op]
    # extr_idx = intfs.index(elig_intfs[np.abs(elig_intfs - extr_op).argmin()])
    # cond_intf = elig_intfs[np.abs(elig_intfs - extr_op).argmin()-lr]
    cond_intf = elig_intfs[1 if lr==-1 else -2]
    # assert elig_intfs[np.abs(elig_intfs - extr_op).argmin()-lr] == cond_intf

    if ops[-1] == extr_op or extr_op is None:
        return False

    # extr_intf = intfs[extr_idx]
    ops_elig = np.array(ops[ops.index([extr_op]):])

    # return len(lr*ops_[ops.index(extr_op):][lr*ops_[ops.index(extr_op):] < lr*np.asarray(intfs)[extr_idx-lr]]) > 0
    # return len([op for op in ops_elig if lr*op < lr*extr_intf]) > 0
    return np.any(lr*ops_elig < lr*cond_intf)

def num_shootpoints(orders, l, r):
    ops = np.array(orders)
    return np.count_nonzero(np.logical_and(ops >= l, ops <= r))